// Maps each blog slug to a topic key + Unsplash search term.
// All slugs sharing a topicKey use the SAME photo file (saves API calls + storage).
// Run via: node scripts/download-photos.mjs

export const slugToTopic = {
  // ===== CITY GUIDES (3-4 slug variants per city, share photo) =====
  // Where to Stay - Europa
  'wo-uebernachten-amsterdam': 'amsterdam',
  'where-to-stay-amsterdam': 'amsterdam',
  'wo-uebernachten-athen': 'athens',
  'where-to-stay-athens': 'athens',
  'wo-uebernachten-barcelona': 'barcelona',
  'where-to-stay-barcelona': 'barcelona',
  'wo-uebernachten-berlin': 'berlin',
  'where-to-stay-berlin': 'berlin',
  'wo-uebernachten-edinburgh': 'edinburgh',
  'where-to-stay-edinburgh': 'edinburgh',
  'wo-uebernachten-lissabon': 'lisbon',
  'where-to-stay-lisbon': 'lisbon',
  'wo-uebernachten-london': 'london',
  'where-to-stay-london': 'london',
  'wo-uebernachten-madrid': 'madrid',
  'where-to-stay-madrid': 'madrid',
  'wo-uebernachten-marseille': 'marseille',
  'where-to-stay-marseille': 'marseille',
  'wo-uebernachten-paris': 'paris',
  'where-to-stay-paris': 'paris',
  'wo-uebernachten-prag': 'prague',
  'where-to-stay-prague': 'prague',
  'wo-uebernachten-rom': 'rome',
  'where-to-stay-rome': 'rome',
  'wo-uebernachten-sevilla': 'seville',
  'where-to-stay-seville': 'seville',
  'wo-uebernachten-budapest': 'budapest',
  'where-to-stay-budapest': 'budapest',
  'donde-alojarse-budapest': 'budapest',
  'wo-uebernachten-florenz': 'florence',
  'where-to-stay-florence': 'florence',
  'donde-alojarse-florencia': 'florence',
  'wo-uebernachten-istanbul': 'istanbul',
  'where-to-stay-istanbul': 'istanbul',
  'donde-alojarse-estambul': 'istanbul',
  'wo-uebernachten-muenchen': 'munich',
  'where-to-stay-munich': 'munich',
  'donde-alojarse-munich': 'munich',
  'wo-uebernachten-santorini': 'santorini',
  'where-to-stay-santorini': 'santorini',
  'donde-alojarse-santorini': 'santorini',
  'wo-uebernachten-wien': 'vienna',
  'where-to-stay-vienna': 'vienna',
  // Where to Stay - Europe cont.
  'wo-uebernachten-warschau': 'warsaw',
  'where-to-stay-warsaw': 'warsaw',
  'donde-alojarse-varsovia': 'warsaw',
  'wo-uebernachten-mykonos': 'mykonos',
  'where-to-stay-mykonos': 'mykonos',
  'donde-alojarse-mykonos': 'mykonos',
  // Where to Stay - LATAM (DE+EN+ES)
  'wo-uebernachten-bogota': 'bogota',
  'where-to-stay-bogota': 'bogota',
  'donde-alojarse-bogota': 'bogota',
  'wo-uebernachten-buenos-aires': 'buenos-aires',
  'where-to-stay-buenos-aires': 'buenos-aires',
  'donde-alojarse-buenos-aires': 'buenos-aires',
  'wo-uebernachten-cancun': 'cancun',
  'where-to-stay-cancun': 'cancun',
  'donde-alojarse-cancun': 'cancun',
  'wo-uebernachten-cartagena': 'cartagena',
  'where-to-stay-cartagena': 'cartagena',
  'donde-alojarse-cartagena': 'cartagena',
  'wo-uebernachten-cusco': 'cusco',
  'where-to-stay-cusco': 'cusco',
  'donde-alojarse-cusco': 'cusco',
  'wo-uebernachten-lima': 'lima',
  'where-to-stay-lima': 'lima',
  'donde-alojarse-lima': 'lima',
  'wo-uebernachten-medellin': 'medellin',
  'where-to-stay-medellin': 'medellin',
  'donde-alojarse-medellin': 'medellin',
  'wo-uebernachten-mendoza': 'mendoza',
  'where-to-stay-mendoza': 'mendoza',
  'donde-alojarse-mendoza': 'mendoza',
  'wo-uebernachten-mexico-city': 'mexico-city',
  'where-to-stay-mexico-city': 'mexico-city',
  'donde-alojarse-ciudad-de-mexico': 'mexico-city',
  'wo-uebernachten-miami': 'miami',
  'where-to-stay-miami': 'miami',
  'donde-alojarse-miami': 'miami',
  'wo-uebernachten-rio-de-janeiro': 'rio-de-janeiro',
  'where-to-stay-rio-de-janeiro': 'rio-de-janeiro',
  'donde-alojarse-rio-de-janeiro': 'rio-de-janeiro',
  'wo-uebernachten-sao-paulo': 'sao-paulo',
  'where-to-stay-sao-paulo': 'sao-paulo',
  'donde-alojarse-sao-paulo': 'sao-paulo',
  'wo-uebernachten-tulum': 'tulum',
  'where-to-stay-tulum': 'tulum',
  'donde-alojarse-tulum': 'tulum',
  // Where to Stay - USA
  'wo-uebernachten-las-vegas': 'las-vegas',
  'where-to-stay-las-vegas': 'las-vegas',
  'wo-uebernachten-los-angeles': 'los-angeles-city',
  'where-to-stay-los-angeles': 'los-angeles-city',
  'los-angeles': 'los-angeles-city',
  'wo-uebernachten-new-orleans': 'new-orleans',
  'where-to-stay-new-orleans': 'new-orleans',
  'wo-uebernachten-new-york': 'new-york',
  'where-to-stay-new-york': 'new-york',
  'wo-uebernachten-san-francisco': 'san-francisco',
  'where-to-stay-san-francisco': 'san-francisco',
  // Where to Stay - Asia
  'wo-uebernachten-bali': 'bali',
  'where-to-stay-bali': 'bali',
  'wo-uebernachten-bangkok': 'bangkok',
  'where-to-stay-bangkok': 'bangkok',
  'wo-uebernachten-hanoi': 'hanoi',
  'where-to-stay-hanoi': 'hanoi',
  'wo-uebernachten-hongkong': 'hong-kong',
  'where-to-stay-hong-kong': 'hong-kong',
  'wo-uebernachten-seoul': 'seoul',
  'where-to-stay-seoul': 'seoul',
  'wo-uebernachten-singapur': 'singapore',
  'where-to-stay-singapore': 'singapore',
  'wo-uebernachten-tokio': 'tokyo',
  'where-to-stay-tokyo': 'tokyo',
  // Where to Stay - Africa
  'wo-uebernachten-cape-town': 'cape-town',
  'where-to-stay-cape-town': 'cape-town',
  'wo-uebernachten-marrakesch': 'marrakech',
  'where-to-stay-marrakech': 'marrakech',

  // ES Where-to-Stay (Steps 2+3, not yet in mapping)
  'donde-alojarse-berlin': 'berlin',
  'donde-alojarse-sevilla': 'seville',
  'donde-alojarse-marsella': 'marseille',
  'donde-alojarse-edimburgo': 'edinburgh',
  'donde-alojarse-ciudad-del-cabo': 'cape-town',
  'donde-alojarse-tokio': 'tokyo',
  'donde-alojarse-bangkok': 'bangkok',
  'donde-alojarse-seul': 'seoul',
  'donde-alojarse-hanoi': 'hanoi',
  'donde-alojarse-nueva-york': 'new-york',
  'donde-alojarse-san-francisco': 'san-francisco',
  'donde-alojarse-los-angeles': 'los-angeles-city',
  'donde-alojarse-las-vegas': 'las-vegas',
  'donde-alojarse-nueva-orleans': 'new-orleans',
  'donde-alojarse-hong-kong': 'hong-kong',
  'donde-alojarse-singapur': 'singapore',
  'donde-alojarse-bali': 'bali',
  'donde-alojarse-amsterdam': 'amsterdam',
  'donde-alojarse-atenas': 'athens',
  'donde-alojarse-barcelona': 'barcelona',
  'donde-alojarse-lisboa': 'lisbon',
  'donde-alojarse-madrid': 'madrid',
  'donde-alojarse-marrakech': 'marrakech',
  'donde-alojarse-paris': 'paris',
  'donde-alojarse-praga': 'prague',
  'donde-alojarse-roma': 'rome',
  'donde-alojarse-viena': 'vienna',
  'donde-alojarse-santorini': 'santorini',

  // ===== TOPIC ARTICLES =====
  // Cities (non-where-to-stay)
  '48-hours-rome': 'rome',
  '48-stunden-rom': 'rome',
  '48-horas-roma': 'rome',
  'madrid-24-hours': 'madrid',
  'madrid-24-stunden': 'madrid',
  'madrid-24-horas': 'madrid',
  'tokio-foodie-reise': 'tokyo-food',
  'tokyo-foodie-trip': 'tokyo-food',
  'tokio-viaje-gastronomico': 'tokyo-food',
  'lisbon-beyond-the-tourist-trail': 'lisbon',
  'lissabon-abseits-der-touristenpfade': 'lisbon',
  'lisboa-fuera-ruta-turistica': 'lisbon',
  'porto-die-unterschaetzte-schwester': 'porto',
  'porto-lisbons-underrated-sister': 'porto',
  'oporto-hermana-subestimada': 'porto',
  'modena-ferrari-museum': 'ferrari-museum',
  'modena-museo-ferrari': 'ferrari-museum',
  'apulien-sueditalien-guide': 'puglia',
  'puglia-southern-italy-guide': 'puglia',
  'apulia-sur-italia-guia': 'puglia',
  'santiago-de-compostela': 'santiago-de-compostela',
  'santiago-de-compostela-ruta': 'santiago-de-compostela',

  // Off the Map / Hidden Gems
  'albania-riviera-hidden-coast': 'albania-coast',
  'albanien-riviera-geheimtipp': 'albania-coast',
  'albania-riviera-escondida': 'albania-coast',
  'faeroeer-inseln-guide': 'faroe-islands',
  'faroe-islands-guide': 'faroe-islands',
  'islas-feroe-guia': 'faroe-islands',
  'iceland-travel-guide': 'iceland',
  'island-reiseguide': 'iceland',
  'islandia-guia-viaje': 'iceland',
  'patagonia-3-week-route': 'patagonia',
  'patagonien-3-wochen-route': 'patagonia',
  'patagonia-3-semanas-ruta': 'patagonia',
  'sansibar-stone-town-guide': 'zanzibar',
  'zanzibar-stone-town-guide': 'zanzibar',
  'zanzibar-stone-town-guia': 'zanzibar',
  'slovenia-green-secret-2026': 'slovenia',
  'slowenien-geheimnis-2026': 'slovenia',
  'eslovenia-secreto-verde-2026': 'slovenia',
  'nordlichter-2026-wo-wann-wie': 'northern-lights',
  'northern-lights-2026-where-when-how': 'northern-lights',
  'auroras-boreales-2026': 'northern-lights',
  'geheimtipps-europa': 'europe-hidden',
  'hidden-gems-europe': 'europe-hidden',
  'joyas-ocultas-europa': 'europe-hidden',

  // Costa Rica
  'costa-rica-rundreise-route': 'costa-rica',
  'costa-rica-road-trip-route': 'costa-rica',
  'costa-rica-ruta-completa': 'costa-rica',
  'costa-rica-surfen': 'costa-rica-surf',
  'costa-rica-surfing': 'costa-rica-surf',
  'costa-rica-surf': 'costa-rica-surf',

  // Travel Tips - Flights
  'guenstig-fliegen-tipps': 'flights-cheap',
  'cheap-flights-tips': 'flights-cheap',
  'consejos-vuelos-baratos': 'flights-cheap',
  'wann-fluege-buchen': 'flights-booking',
  'when-to-book-flights': 'flights-booking',
  'cuando-reservar-vuelos': 'flights-booking',
  'open-jaw-tickets-reise-hack': 'world-map',
  'open-jaw-tickets-travel-hack': 'world-map',
  'open-jaw-tickets-truco-viaje': 'world-map',
  'hidden-city-ticketing-erklaert': 'flight-ticket',
  'hidden-city-ticketing-explained': 'flight-ticket',
  'hidden-city-ticketing-explicado': 'flight-ticket',
  'business-class': 'business-class',
  'business-class-worth-it': 'business-class',
  'business-class-vale-la-pena': 'business-class',
  'business-class-ohne-meilen': 'business-class',
  'business-class-without-miles': 'business-class',
  'business-class-sin-millas': 'business-class',
  'lounge-zugang-ohne-business-ticket': 'airport-lounge',
  'lounge-access-without-business-ticket': 'airport-lounge',
  'acceso-sala-vip-sin-business': 'airport-lounge',
  'airport-hacks': 'airport',
  'trucos-aeropuerto': 'airport',
  'jetlag-schnell-ueberwinden': 'jet-lag',
  'jet-lag-fast-recovery': 'jet-lag',
  'superar-jetlag-rapido': 'jet-lag',
  'stopover-tourismus-guide': 'stopover',
  'stopover-tourism-guide': 'stopover',
  'guia-stopover-turismo': 'stopover',
  'bahn-vs-flieger-europa-2026': 'train-station',
  'train-vs-plane-europe-2026': 'train-station',
  'tren-vs-avion-europa-2026': 'train-station',
  'normas-powerbank-equipaje-mano': 'powerbank',

  // AI & Travel
  'ki-veraendert-reiseplanung': 'ai-travel',
  'ai-changing-travel-planning': 'ai-travel',
  'ia-cambia-planificacion-viajes': 'ai-travel',
  'ki-reiseplaner-vs-reisebuero': 'ai-vs-agent',
  'ai-trip-planner-vs-travel-agent': 'ai-vs-agent',
  'planificador-ia-vs-agencia-viajes': 'ai-vs-agent',
  'ki-tools-reise-vergleich': 'ai-tools',
  'ai-tools-travel-comparison': 'ai-tools',
  'herramientas-ia-comparativa-viajes': 'ai-tools',
  'ki-vergleich-reiseplanung-2026': 'ai-comparison',
  'ai-comparison-trip-planning-2026': 'ai-comparison',
  'ia-comparativa-planificacion-2026': 'ai-comparison',
  'was-ist-zercy': 'travel-planning',
  'what-is-zercy': 'travel-planning',
  'que-es-zercy': 'travel-planning',
  'zercy-logbook': 'travel-journal',
  'zercy-logbook-que-es': 'travel-journal',

  // Smart Travel
  'booking-vs-direkt-buchen': 'hotel-booking',
  'booking-vs-direct-hotel-booking': 'hotel-booking',
  'reservar-online-o-directo': 'hotel-booking',
  'airbnb-vs-hotel-vergleich': 'apartment-vs-hotel',
  'airbnb-vs-hotel-comparison': 'apartment-vs-hotel',
  'airbnb-vs-hotel-comparacion': 'apartment-vs-hotel',
  'booking-genius-programm-lohnt-es-sich': 'booking-genius',
  'booking-genius-program-worth-it': 'booking-genius',
  'booking-genius-vale-la-pena': 'booking-genius',
  'booking-apartments-vs-airbnb': 'apartment-vs-hotel',
  'apartamento-vs-hotel-cual-elegir': 'apartment-vs-hotel',
  'mietwagen-check': 'rental-car',
  'rental-car-checklist': 'rental-car',
  'checklist-alquiler-coche': 'rental-car',
  'mietwagen-versteckte-kosten-vermeiden': 'rental-car-keys',
  'rental-car-hidden-costs-avoid': 'rental-car-keys',
  'costes-ocultos-alquiler-coche': 'rental-car-keys',
  'mietwagen-consolidator-guenstiger-fahren': 'car-keys-money',
  'rental-consolidators-save-money': 'car-keys-money',
  'consolidadores-alquiler-ahorrar': 'car-keys-money',
  'reiseversicherung-was-lohnt-sich': 'travel-insurance',
  'travel-insurance-worth-it-2026': 'travel-insurance',
  'seguro-viaje-vale-la-pena': 'travel-insurance',
  'cyber-sicherheit-reisen': 'cyber-security',
  'cyber-security-travel-2026': 'cyber-security',
  'ciberseguridad-viajeros': 'cyber-security',
  'beste-travel-apps-2026': 'travel-apps',
  'best-travel-apps-2026': 'travel-apps',
  'mejores-apps-viaje-2026': 'travel-apps',

  // On the Move
  'zugreisen-europa': 'train-europe',
  'train-travel-europe': 'train-europe',
  'viajes-tren-europa': 'train-europe',
  'nachtzuege-europa-2026': 'night-train',
  'night-trains-europe-2026': 'night-train',
  'trenes-nocturnos-europa-2026': 'night-train',
  'roadtrip-etappen-planung': 'road-trip',
  'road-trip-stages-planning': 'road-trip',
  'roadtrip-planificacion-etapas': 'road-trip',
  'kreuzfahrt-staedte-verlaengern': 'cruise-port',
  'cruise-extend-port-cities': 'cruise-port',
  'cruceros-ampliar-ciudades': 'cruise-port',

  // Carry-On Only
  'nur-handgepaeck': 'carry-on-bag',
  'carry-on-only': 'carry-on-bag',
  'solo-equipaje-de-mano': 'carry-on-bag',
  'capsule-wardrobe-handgepaeck': 'capsule-wardrobe',
  'capsule-wardrobe-carry-on': 'capsule-wardrobe',
  'maleta-capsula-equipaje-mano': 'capsule-wardrobe',
  'powerbank-regeln-handgepaeck-2026': 'powerbank',
  'powerbank-rules-carry-on-2026': 'powerbank',
  'handgepaeck-fluessigkeiten-regeln-2026': 'carry-on-liquids',
  'carry-on-liquids-rules-2026': 'carry-on-liquids',
  'liquidos-equipaje-mano-2026': 'carry-on-liquids',

  // Travel Green
  'co2-kompensation-fliegen': 'forest-airplane',
  'flight-carbon-offsets-truth': 'forest-airplane',
  'compensacion-co2-vuelos': 'forest-airplane',
  'plastik-frei-reisen-tipps': 'reusable-bottle',
  'plastic-free-travel-tips': 'reusable-bottle',
  'viaje-sin-plastico-consejos': 'reusable-bottle',
  'slow-travel-bedeutet-was': 'slow-travel',
  'slow-travel-what-it-really-means': 'slow-travel',
  'slow-travel-que-significa': 'slow-travel',

  // Lifestyle / Special
  'workation-steuern-2026': 'workation',
  'workation-tax-rules-2026': 'workation',
  'workation-impuestos-2026': 'workation',
  'sabbatical-planen-guide': 'sabbatical',
  'sabbatical-planning-guide': 'sabbatical',
  'sabbatical-guia-planificacion': 'sabbatical',
  'solo-reisen-frauen-sicher': 'solo-female-travel',
  'solo-travel-women-safe-countries': 'solo-female-travel',
  'viaje-solo-mujeres-seguro': 'solo-female-travel',
  'mit-hund-europa-reisen': 'travel-with-dog',
  'traveling-with-dog-europe': 'travel-with-dog',
  'viajar-con-perro-europa': 'travel-with-dog',
  'reisen-mit-baby-erste-fluege': 'baby-travel',
  'traveling-with-baby-first-flights': 'baby-travel',
  'viajar-con-bebe-primer-vuelo': 'baby-travel',

  // Hotels (general)
  'boutique-hotels': 'boutique-hotel',
  'hoteles-boutique-guia': 'boutique-hotel',
  'riads-marokko-guide': 'morocco-riad',
  'morocco-riads-guide': 'morocco-riad',
  'riads-marruecos-guia': 'morocco-riad',

  // ===== WHERE TO STAY BATCH 3 (2026-05-09) =====
  // Antalya
  'wo-uebernachten-antalya': 'antalya',
  'where-to-stay-antalya': 'antalya',
  'donde-alojarse-antalya': 'antalya',
  // Phuket
  'wo-uebernachten-phuket': 'phuket',
  'where-to-stay-phuket': 'phuket',
  'donde-alojarse-phuket': 'phuket',
  // Taipei
  'wo-uebernachten-taipei': 'taipei',
  'where-to-stay-taipei': 'taipei',
  'donde-alojarse-taipei': 'taipei',
  // Venice
  'wo-uebernachten-venedig': 'venice',
  'where-to-stay-venice': 'venice',
  'donde-alojarse-venecia': 'venice',
  // Dublin
  'wo-uebernachten-dublin': 'dublin',
  'where-to-stay-dublin': 'dublin',
  'donde-alojarse-dublin': 'dublin',
  // Doha
  'wo-uebernachten-doha': 'doha',
  'where-to-stay-doha': 'doha',
  'donde-alojarse-doha': 'doha',
  // Abu Dhabi
  'wo-uebernachten-abu-dhabi': 'abu-dhabi',
  'where-to-stay-abu-dhabi': 'abu-dhabi',
  'donde-alojarse-abu-dhabi': 'abu-dhabi',
  // Ho Chi Minh City
  'wo-uebernachten-ho-chi-minh-stadt': 'ho-chi-minh',
  'where-to-stay-ho-chi-minh-city': 'ho-chi-minh',
  'donde-alojarse-ho-chi-minh': 'ho-chi-minh',
  // Toronto
  'wo-uebernachten-toronto': 'toronto',
  'where-to-stay-toronto': 'toronto',
  'donde-alojarse-toronto': 'toronto',
  // Stockholm
  'wo-uebernachten-stockholm': 'stockholm',
  'where-to-stay-stockholm': 'stockholm',
  'donde-alojarse-estocolmo': 'stockholm',

  // ===== WHERE TO STAY BATCH 2 (2026-05-09) =====
  // Dubai
  'wo-uebernachten-dubai': 'dubai',
  'where-to-stay-dubai': 'dubai',
  'donde-alojarse-dubai': 'dubai',
  // Kuala Lumpur
  'wo-uebernachten-kuala-lumpur': 'kuala-lumpur',
  'where-to-stay-kuala-lumpur': 'kuala-lumpur',
  'donde-alojarse-kuala-lumpur': 'kuala-lumpur',
  // Osaka
  'wo-uebernachten-osaka': 'osaka',
  'where-to-stay-osaka': 'osaka',
  'donde-alojarse-osaka': 'osaka',
  // Milan
  'wo-uebernachten-mailand': 'milan',
  'where-to-stay-milan': 'milan',
  'donde-alojarse-milan': 'milan',
  // Sydney
  'wo-uebernachten-sydney': 'sydney',
  'where-to-stay-sydney': 'sydney',
  'donde-alojarse-sydney': 'sydney',
  // Copenhagen
  'wo-uebernachten-kopenhagen': 'copenhagen',
  'where-to-stay-copenhagen': 'copenhagen',
  'donde-alojarse-copenhague': 'copenhagen',
  // Porto (Where to Stay — shares photo with porto topic)
  'wo-uebernachten-porto': 'porto',
  'where-to-stay-porto': 'porto',
  'donde-alojarse-oporto': 'porto',
  // Kyoto
  'wo-uebernachten-kyoto': 'kyoto',
  'where-to-stay-kyoto': 'kyoto',
  'donde-alojarse-kioto': 'kyoto',
  // Tbilisi
  'wo-uebernachten-tiflis': 'tbilisi',
  'where-to-stay-tbilisi': 'tbilisi',
  'donde-alojarse-tiflis': 'tbilisi',
  // Valencia
  'wo-uebernachten-valencia': 'valencia',
  'where-to-stay-valencia': 'valencia',
  'donde-alojarse-valencia': 'valencia',

  // Havana
  'wo-uebernachten-havanna': 'havana',
  'where-to-stay-havana': 'havana',
  'donde-alojarse-la-habana': 'havana',
  // Vancouver
  'wo-uebernachten-vancouver': 'vancouver',
  'where-to-stay-vancouver': 'vancouver',
  'donde-alojarse-vancouver': 'vancouver',
  // Chicago
  'wo-uebernachten-chicago': 'chicago',
  'where-to-stay-chicago': 'chicago',
  'donde-alojarse-chicago': 'chicago',

  // ===== NEW BATCH (2026-05-09) =====
  // Greek Islands
  'griechenland-inseln-vergleich': 'greek-islands',
  'greek-islands-comparison': 'greek-islands',
  'islas-griegas-comparativa': 'greek-islands',
  // Thailand
  'thailand-route-2-wochen': 'thailand',
  'thailand-2-week-itinerary': 'thailand',
  'tailandia-2-semanas-ruta': 'thailand',
  // Dubai
  'dubai-reiseguide': 'dubai',
  'dubai-travel-guide': 'dubai',
  'dubai-guia-viaje': 'dubai',
  // Hotel Upgrade
  'hotel-upgrade-gratis-tipps': 'hotel-upgrade',
  'hotel-upgrade-free-tips': 'hotel-upgrade',
  'trucos-upgrade-hotel-gratis': 'hotel-upgrade',
  // Family Travel Europe
  'familienurlaub-europa-ziele': 'family-vacation',
  'family-travel-europe-best-destinations': 'family-vacation',
  'viaje-familiar-europa-mejores-destinos': 'family-vacation',
  // Budget Travel
  'reisen-kleines-budget-tipps': 'budget-travel',
  'travel-tight-budget-tips': 'budget-travel',
  'viajar-con-poco-dinero-consejos': 'budget-travel',
  // Autumn Travel
  'beste-herbstziele-reisen': 'autumn-travel',
  'best-autumn-travel-destinations': 'autumn-travel',
  'mejores-destinos-otono-viaje': 'autumn-travel',
  // Maldives
  'malediven-reiseguide-tipps': 'maldives',
  'maldives-travel-guide-tips': 'maldives',
  'maldivas-guia-viaje-2026': 'maldives',
  // Luxury on Budget
  'luxusreisen-guenstig-tipps': 'luxury-travel',
  'luxury-travel-budget-tips': 'luxury-travel',
  'viaje-lujo-economico-trucos': 'luxury-travel',
  // Japan Beyond Tokyo
  'japan-jenseits-von-tokio': 'japan-kyoto',
  'japan-beyond-tokyo-guide': 'japan-kyoto',
  'japon-mas-alla-de-tokio': 'japan-kyoto',

  // ===== 75 NEW TOPIC ARTICLES (2026-05-09) — DE + EN + ES =====
  'beste-reise-kreditkarten-2026': 'miles-points',
  'best-travel-credit-cards-2026': 'miles-points',
  'mejores-tarjetas-credito-viaje-2026': 'miles-points',
  'neuseeland-reiseguide': 'new-zealand',
  'new-zealand-travel-guide': 'new-zealand',
  'guia-viaje-nueva-zelanda': 'new-zealand',
  'schottland-highlands-roadtrip': 'scotland',
  'scottish-highlands-road-trip': 'scotland',
  'road-trip-highlands-escocia': 'scotland',
  'interrail-guide-2026': 'train-europe',
  'guia-interrail-2026': 'train-europe',
  '48-stunden-istanbul': 'istanbul',
  '48-hours-istanbul': 'istanbul',
  '48-horas-estambul': 'istanbul',
  '48-stunden-barcelona': 'barcelona',
  '48-hours-barcelona': 'barcelona',
  '48-horas-barcelona': 'barcelona',
  'wien-am-wochenende': 'vienna',
  'vienna-for-a-weekend': 'vienna',
  'viena-fin-de-semana': 'vienna',
  'vietnam-2-wochen-route': 'vietnam',
  'vietnam-2-week-route': 'vietnam',
  'vietnam-2-semanas-ruta': 'vietnam',
  'marokko-roadtrip': 'marrakech',
  'morocco-road-trip': 'marrakech',
  'road-trip-marruecos': 'marrakech',
  'kolumbien-reiseguide': 'cartagena',
  'colombia-travel-guide': 'cartagena',
  'guia-viaje-colombia': 'cartagena',
  'kroatien-inseln-hopping': 'croatia-islands',
  'croatia-island-hopping': 'croatia-islands',
  'islas-croacia-island-hopping': 'croatia-islands',
  'flugverspaetung-deine-rechte': 'flight-ticket',
  'flight-delay-rights': 'flight-ticket',
  'retrasos-vuelo-derechos': 'flight-ticket',
  'handgepaeck-vs-aufgegebenes-gepaeck': 'carry-on-bag',
  'carry-on-vs-checked-luggage': 'carry-on-bag',
  'equipaje-mano-vs-facturado': 'carry-on-bag',
  'meilen-punkte-anfaenger': 'miles-points',
  'miles-points-beginners': 'miles-points',
  'millas-puntos-principiantes': 'miles-points',
  'reisefotografie-tipps': 'travel-photography',
  'travel-photography-tips': 'travel-photography',
  'fotografia-viaje-consejos': 'travel-photography',
  'auslands-sim-guide': 'travel-apps',
  'local-sim-card-guide': 'travel-apps',
  'guia-sim-extranjero': 'travel-apps',
  'osaka-vs-kyoto': 'kyoto',
  'bangkok-3-tage': 'bangkok',
  'bangkok-3-days': 'bangkok',
  'bangkok-3-dias': 'bangkok',
  'peru-reiseguide-highlights': 'peru',
  'peru-travel-guide-highlights': 'peru',
  'peru-guia-viaje-highlights': 'peru',
  'hostel-guide-richtig-buchen': 'budget-travel',
  'hostel-booking-guide': 'budget-travel',
  'guia-reservar-hostel': 'budget-travel',
  'reisen-nach-60-tipps': 'senior-travel',
  'travel-after-60-tips': 'senior-travel',
  'viajar-despues-60-consejos': 'senior-travel',
  'airbnb-experiences-lohnt-sich': 'apartment-vs-hotel',
  'airbnb-experiences-worth-it': 'apartment-vs-hotel',
  'airbnb-experiences-vale-la-pena': 'apartment-vs-hotel',
  'beste-offline-reise-apps': 'travel-apps',
  'best-offline-travel-apps': 'travel-apps',
  'mejores-apps-viaje-sin-internet': 'travel-apps',
  'langstreckenflug-mit-kindern': 'baby-travel',
  'long-haul-flight-with-kids': 'baby-travel',
  'vuelo-largo-con-ninos': 'baby-travel',
  'skiurlaub-europa-beste-orte': 'ski-resort',
  'ski-holidays-europe-best-resorts': 'ski-resort',
  'vacaciones-ski-europa-mejores-destinos': 'ski-resort',

  // ===== MISSING TOP CITIES BATCH (2026-05-09) =====
  // India
  'wo-uebernachten-mumbai': 'mumbai',
  'where-to-stay-mumbai': 'mumbai',
  'donde-alojarse-mumbai': 'mumbai',
  'wo-uebernachten-delhi': 'delhi',
  'where-to-stay-delhi': 'delhi',
  'donde-alojarse-delhi': 'delhi',
  'wo-uebernachten-goa': 'goa',
  'where-to-stay-goa': 'goa',
  'donde-alojarse-goa': 'goa',
  // Oceania
  'wo-uebernachten-auckland': 'auckland',
  'where-to-stay-auckland': 'auckland',
  'donde-alojarse-auckland': 'auckland',
  // South America
  'wo-uebernachten-santiago': 'santiago',
  'where-to-stay-santiago': 'santiago',
  'donde-alojarse-santiago': 'santiago',
  'wo-uebernachten-sao-paulo': 'sao-paulo',
  'where-to-stay-sao-paulo': 'sao-paulo',
  'donde-alojarse-sao-paulo': 'sao-paulo',
  // Mexico
  'wo-uebernachten-playa-del-carmen': 'playa-del-carmen',
  'where-to-stay-playa-del-carmen': 'playa-del-carmen',
  'donde-alojarse-playa-del-carmen': 'playa-del-carmen',
  'wo-uebernachten-puerto-vallarta': 'puerto-vallarta',
  'where-to-stay-puerto-vallarta': 'puerto-vallarta',
  'donde-alojarse-puerto-vallarta': 'puerto-vallarta',
  'wo-uebernachten-oaxaca': 'oaxaca',
  'where-to-stay-oaxaca': 'oaxaca',
  'donde-alojarse-oaxaca': 'oaxaca',
  // Europe
  'wo-uebernachten-bruessel': 'brussels',
  'where-to-stay-brussels': 'brussels',
  'donde-alojarse-bruselas': 'brussels',
  'wo-uebernachten-zuerich': 'zurich',
  'where-to-stay-zurich': 'zurich',
  'donde-alojarse-zurich': 'zurich',
  'wo-uebernachten-oslo': 'oslo',
  'where-to-stay-oslo': 'oslo',
  'donde-alojarse-oslo': 'oslo',
  'wo-uebernachten-warschau': 'warsaw',
  'where-to-stay-warsaw': 'warsaw',
  'donde-alojarse-varsovia': 'warsaw',
  'wo-uebernachten-mykonos': 'mykonos',
  'where-to-stay-mykonos': 'mykonos',
  'donde-alojarse-mykonos': 'mykonos',
  // Africa
  'wo-uebernachten-johannesburg': 'johannesburg',
  'where-to-stay-johannesburg': 'johannesburg',
  'donde-alojarse-johannesburg': 'johannesburg',

  // ===== REPLACEMENT BATCH (2026-05-09) — replaces deleted forbidden destinations =====
  // Dubrovnik
  'wo-uebernachten-dubrovnik': 'dubrovnik',
  'where-to-stay-dubrovnik': 'dubrovnik',
  'donde-alojarse-dubrovnik': 'dubrovnik',
  // Reykjavik
  'wo-uebernachten-reykjavik': 'reykjavik',
  'where-to-stay-reykjavik': 'reykjavik',
  'donde-alojarse-reikiavik': 'reykjavik',
  // Krakow
  'wo-uebernachten-krakau': 'krakow',
  'where-to-stay-krakow': 'krakow',
  'donde-alojarse-cracovia': 'krakow',
  // Valletta
  'wo-uebernachten-valletta': 'valletta',
  'where-to-stay-valletta': 'valletta',
  'donde-alojarse-la-valeta': 'valletta',
  // Chiang Mai
  'wo-uebernachten-chiang-mai': 'chiang-mai',
  'where-to-stay-chiang-mai': 'chiang-mai',
  'donde-alojarse-chiang-mai': 'chiang-mai',
  // Nairobi
  'wo-uebernachten-nairobi': 'nairobi',
  'where-to-stay-nairobi': 'nairobi',
  'donde-alojarse-nairobi': 'nairobi',

  // ===== BATCH 2026-05-11 — Tallinn, Riga, Route 66 =====
  // Tallinn
  'wo-uebernachten-tallinn': 'tallinn',
  'where-to-stay-tallinn': 'tallinn',
  'donde-alojarse-tallin': 'tallinn',
  // Riga
  'wo-uebernachten-riga': 'riga',
  'where-to-stay-riga': 'riga',
  'donde-alojarse-riga': 'riga',
  // Route 66
  'route-66-usa-roadtrip': 'route-66',
  'route-66-usa-road-trip': 'route-66',
  'ruta-66-estados-unidos-road-trip': 'route-66',
  // Nice / Nizza
  'wo-uebernachten-nizza': 'nice',
  'where-to-stay-nice': 'nice',
  'donde-alojarse-niza': 'nice',
  // Bologna
  'wo-uebernachten-bologna': 'bologna',
  'where-to-stay-bologna': 'bologna',
  'donde-alojarse-bolonia': 'bologna',
  // Bali vs. Lombok comparison
  'bali-vs-lombok-vergleich': 'bali-lombok',
  'bali-vs-lombok-comparison': 'bali-lombok',
  'bali-vs-lombok-comparacion': 'bali-lombok',

  // ===== BATCH 2026-05-10 — 5 City Guides + 5 Themenartikel =====
  // Naples / Neapel
  'wo-uebernachten-neapel': 'neapel',
  'where-to-stay-naples': 'neapel',
  'donde-alojarse-napoles': 'neapel',
  // Malaga
  'wo-uebernachten-malaga': 'malaga',
  'where-to-stay-malaga': 'malaga',
  'donde-alojarse-malaga': 'malaga',
  // Melbourne
  'wo-uebernachten-melbourne': 'melbourne',
  'where-to-stay-melbourne': 'melbourne',
  'donde-alojarse-melbourne': 'melbourne',
  // Jaipur
  'wo-uebernachten-jaipur': 'jaipur',
  'where-to-stay-jaipur': 'jaipur',
  'donde-alojarse-jaipur': 'jaipur',
  // Washington DC
  'wo-uebernachten-washington-dc': 'washington-dc',
  'where-to-stay-washington-dc': 'washington-dc',
  'donde-alojarse-washington-dc': 'washington-dc',
  // Reisekreditkarte
  'reisekreditkarte-2026': 'reisekreditkarte',
  'travel-credit-card-2026': 'reisekreditkarte',
  'tarjeta-credito-viajes-2026': 'reisekreditkarte',
  // Frühbucher vs. Last Minute
  'fruehbucher-vs-last-minute': 'fruehbucher-last-minute',
  'early-booking-vs-last-minute': 'fruehbucher-last-minute',
  'reserva-anticipada-vs-last-minute': 'fruehbucher-last-minute',
  // Hostel oder Hotel
  'hostel-oder-hotel-2026': 'hostel',
  'hostel-vs-hotel-2026': 'hostel',
  'hostel-o-hotel-2026': 'hostel',
  // Geld im Ausland
  'geld-im-ausland-tipps': 'geld-ausland',
  'money-abroad-tips': 'geld-ausland',
  'dinero-en-el-extranjero-consejos': 'geld-ausland',
  // Familienurlaub mit Kindern
  'familienurlaub-mit-kindern-tipps': 'familienurlaub',
  'family-vacation-with-kids-tips': 'familienurlaub',
  'vacaciones-en-familia-consejos': 'familienurlaub',

  // ===== BATCH 2026-05-11 — Siem Reap + Sailing + Hiking =====
  // Siem Reap
  'wo-uebernachten-siem-reap': 'siem-reap',
  'where-to-stay-siem-reap': 'siem-reap',
  'donde-alojarse-siem-reap': 'siem-reap',
  // Sailing Holiday (Beginners)
  'segelurlaub-einsteiger-guide': 'sailing',
  'sailing-holiday-beginners-guide': 'sailing',
  'vacaciones-vela-principiantes': 'sailing',
  // Long-Distance Hiking Trails
  'fernwanderwege-welt-top-routen': 'hiking-trails',
  'best-long-distance-hiking-trails-world': 'hiking-trails',
  'mejores-rutas-senderismo-mundo': 'hiking-trails',

  // ===== BATCH 2026-05-11 — Colombo + Tipping + Winter Sun =====
  // Colombo
  'wo-uebernachten-colombo': 'colombo',
  'where-to-stay-colombo': 'colombo',
  'donde-alojarse-colombo': 'colombo',
  // Tipping worldwide
  'trinkgeld-weltweit-guide': 'tipping-worldwide',
  'tipping-culture-worldwide-guide': 'tipping-worldwide',
  'propinas-en-el-mundo-guia': 'tipping-worldwide',
  // Winter sun destinations
  'wintersonnen-destinationen-januar': 'winter-sun',
  'winter-sun-destinations-january': 'winter-sun',
  'destinos-sol-invierno-enero': 'winter-sun',

  // ===== BATCH 2026-05-11 — 30 new articles (agents 3-6, 8-9) =====
  // Salzburg
  'wo-uebernachten-salzburg': 'salzburg',
  'where-to-stay-salzburg': 'salzburg',
  'donde-alojarse-salzburgo': 'salzburg',
  // Split
  'wo-uebernachten-split': 'split',
  'where-to-stay-split': 'split',
  'donde-alojarse-split': 'split',
  // Südostasien Budget
  'suedostasien-budget-reisen': 'southeast-asia-budget',
  'southeast-asia-budget-travel': 'southeast-asia-budget',
  'sudeste-asiatico-viaje-economico': 'southeast-asia-budget',
  // Tenerife
  'wo-uebernachten-teneriffa': 'tenerife',
  'where-to-stay-tenerife': 'tenerife',
  'donde-alojarse-tenerife': 'tenerife',
  // Boston
  'wo-uebernachten-boston': 'boston',
  'where-to-stay-boston': 'boston',
  'donde-alojarse-boston': 'boston',
  // East Africa Safari
  'safari-ostafrika-guide': 'east-africa-safari',
  'east-africa-safari-guide': 'east-africa-safari',
  'safari-africa-oriental-guia': 'east-africa-safari',
  // Seattle
  'wo-uebernachten-seattle': 'seattle',
  'where-to-stay-seattle': 'seattle',
  'donde-alojarse-seattle': 'seattle',
  // Nashville
  'wo-uebernachten-nashville': 'nashville',
  'where-to-stay-nashville': 'nashville',
  'donde-alojarse-nashville': 'nashville',
  // Digital Nomad Visa
  'digital-nomad-visum-laender-2026': 'digital-nomad-visa',
  'digital-nomad-visa-countries-2026': 'digital-nomad-visa',
  'visa-nomada-digital-paises-2026': 'digital-nomad-visa',
  // Penang
  'wo-uebernachten-penang': 'penang',
  'where-to-stay-penang': 'penang',
  'donde-alojarse-penang': 'penang',
  // Best Beaches Europe
  'schoenste-straende-europa-2026': 'europe-beaches',
  'best-beaches-europe-2026': 'europe-beaches',
  'mejores-playas-europa-2026': 'europe-beaches',
  // Wellness & Spa
  'wellness-spa-reisen-destinationen': 'wellness-spa',
  'wellness-spa-travel-destinations': 'wellness-spa',
  'viajes-wellness-spa-destinos': 'wellness-spa',
  // Brisbane
  'wo-uebernachten-brisbane': 'brisbane',
  'where-to-stay-brisbane': 'brisbane',
  'donde-alojarse-brisbane': 'brisbane',
  // Food Travel
  'food-travel-essen-wie-einheimischer': 'food-travel',
  'food-travel-eat-like-a-local': 'food-travel',
  'turismo-gastronomico-comer-como-local': 'food-travel',
  // Travel Mistakes
  'reisefehler-vermeiden-klassische-fehler': 'travel-mistakes',
  'travel-mistakes-avoid-common': 'travel-mistakes',
  'errores-viaje-evitar-clasicos': 'travel-mistakes',
  // Cairo
  'wo-uebernachten-kairo': 'cairo',
  'where-to-stay-cairo': 'cairo',
  'donde-alojarse-el-cairo': 'cairo',
  // Hotel Categories
  'hotel-kategorien-erklaert': 'hotel-categories',
  'hotel-categories-explained': 'hotel-categories',
  'categorias-hotel-explicadas': 'hotel-categories',
  // Teen Travel
  'reisen-mit-teenagern-tipps': 'teen-travel',
  'travel-with-teenagers-tips': 'teen-travel',
  'viajar-con-adolescentes-consejos': 'teen-travel',
  // Cruise Beginners Guide
  'kreuzfahrt-einsteiger-guide': 'cruise-beginner',
  'cruise-beginners-guide': 'cruise-beginner',
  'crucero-guia-principiantes': 'cruise-beginner',
  // House Swap Guide
  'wohnungstausch-urlaub-guide': 'house-swap',
  'house-swap-travel-guide': 'house-swap',
  'intercambio-casas-guia-viajeros': 'house-swap',
  // Visa on Arrival 2026
  'visa-on-arrival-laender-2026': 'visa-on-arrival',
  'visa-on-arrival-countries-2026': 'visa-on-arrival',
  'paises-visa-llegada-2026': 'visa-on-arrival',

  // ===== BATCH 2026-05-11 — Bilbao + Granada + Algarve =====
  // Bilbao
  'wo-uebernachten-bilbao': 'bilbao',
  'where-to-stay-bilbao': 'bilbao',
  'donde-alojarse-bilbao': 'bilbao',
  // Granada
  'wo-uebernachten-granada': 'granada',
  'where-to-stay-granada': 'granada',
  'donde-alojarse-granada': 'granada',
  // Algarve (thematic)
  'algarve-reisefuehrer-2026': 'algarve',
  'algarve-travel-guide-2026': 'algarve',
  'algarve-guia-viaje-2026': 'algarve',

  // ===== BATCH 2026-05-11 — Kotor + Bucharest + Winter Europe =====
  // Kotor
  'wo-uebernachten-kotor': 'kotor',
  'where-to-stay-kotor': 'kotor',
  'donde-alojarse-kotor': 'kotor',
  // Bucharest
  'wo-uebernachten-bukarest': 'bucharest',
  'where-to-stay-bucharest': 'bucharest',
  'donde-alojarse-bucarest': 'bucharest',
  // Winter Europe cities (thematic)
  'europaeische-staedte-winter-tipps': 'winter-europe',
  'european-cities-winter-guide': 'winter-europe',
  'ciudades-europeas-invierno-guia': 'winter-europe',

  // ===== BATCH 2026-05-11 — agents 1, 3, 5, 6, 7, 8, 10 =====
  // Bordeaux
  'wo-uebernachten-bordeaux': 'bordeaux',
  'where-to-stay-bordeaux': 'bordeaux',
  'donde-alojarse-burdeos': 'bordeaux',
  // Palma de Mallorca
  'wo-uebernachten-palma-de-mallorca': 'palma-de-mallorca',
  'where-to-stay-palma-de-mallorca': 'palma-de-mallorca',
  'donde-alojarse-palma-de-mallorca': 'palma-de-mallorca',
  // Campervan Europe
  'campervan-urlaub-europa': 'campervan-europe',
  'campervan-europe-guide': 'campervan-europe',
  'campervan-vacaciones-europa': 'campervan-europe',
  // Lanzarote
  'wo-uebernachten-lanzarote': 'lanzarote',
  'where-to-stay-lanzarote': 'lanzarote',
  'donde-alojarse-lanzarote': 'lanzarote',
  // Ljubljana
  'wo-uebernachten-ljubljana': 'ljubljana',
  'where-to-stay-ljubljana': 'ljubljana',
  'donde-alojarse-liubliana': 'ljubljana',
  // Diving & Snorkeling
  'tauchen-schnorcheln-reiseziele': 'diving-snorkeling',
  'diving-snorkeling-destinations': 'diving-snorkeling',
  'buceo-snorkel-destinos-2026': 'diving-snorkeling',
  // Vilnius
  'wo-uebernachten-vilnius': 'vilnius',
  'where-to-stay-vilnius': 'vilnius',
  'donde-alojarse-vilna': 'vilnius',
  // Montreal
  'wo-uebernachten-montreal': 'montreal',
  'where-to-stay-montreal': 'montreal',
  'donde-alojarse-montreal': 'montreal',
  // Switzerland
  'schweiz-reise-highlights-guide': 'switzerland',
  'switzerland-travel-highlights': 'switzerland',
  'suiza-guia-viaje-2026': 'switzerland',
  // Guadalajara
  'wo-uebernachten-guadalajara': 'guadalajara',
  'where-to-stay-guadalajara': 'guadalajara',
  'donde-alojarse-guadalajara': 'guadalajara',
  // Kathmandu
  'wo-uebernachten-kathmandu': 'kathmandu',
  'where-to-stay-kathmandu': 'kathmandu',
  'donde-alojarse-katmandu': 'kathmandu',
  // City Cards
  'city-cards-museumspaesse-lohnen-sich': 'city-cards',
  'city-cards-museum-passes-worth-it': 'city-cards',
  'tarjetas-ciudad-museos-vale-la-pena': 'city-cards',
  // Hoi An
  'wo-uebernachten-hoi-an': 'hoi-an',
  'where-to-stay-hoi-an': 'hoi-an',
  'donde-alojarse-hoi-an': 'hoi-an',
  // Queenstown
  'wo-uebernachten-queenstown': 'queenstown',
  'where-to-stay-queenstown': 'queenstown',
  'donde-alojarse-queenstown': 'queenstown',
  // Airport Transfer
  'flughafentransfer-tipps-2026': 'airport-transfer',
  'airport-transfer-guide-2026': 'airport-transfer',
  'transporte-aeropuerto-guia-2026': 'airport-transfer',
  // Funchal
  'wo-uebernachten-funchal': 'funchal',
  'where-to-stay-funchal': 'funchal',
  'donde-alojarse-funchal': 'funchal',
  // Yoga Retreat
  'yoga-retreat-reiseziele-2026': 'yoga-retreat',
  'yoga-retreat-destinations-2026': 'yoga-retreat',
  'yoga-retiros-destinos-2026': 'yoga-retreat',
  // Surf for Beginners
  'surfurlaub-anfaenger-destinations': 'surf-beginner',
  'surfing-holiday-beginners-guide': 'surf-beginner',
  'viaje-surf-principiantes-destinos': 'surf-beginner',
  // Caribbean Island Hopping
  'inselhopping-karibik-guide': 'caribbean-islands',
  'caribbean-island-hopping-guide': 'caribbean-islands',
  'islas-caribe-island-hopping-guia': 'caribbean-islands',
  // Package Tour vs. Independent
  'pauschalreise-vs-individualreise': 'package-tour-vs-independent',
  'package-tour-vs-independent-travel': 'package-tour-vs-independent',
  'viaje-organizado-vs-independiente': 'package-tour-vs-independent',
  // Best Beaches Worldwide
  'beste-badeziele-weltweit-2026': 'best-beaches-world',
  'best-beach-destinations-worldwide-2026': 'best-beaches-world',
  'mejores-destinos-playa-mundo-2026': 'best-beaches-world',
};

// Topic key -> Unsplash search query (used when downloading)
export const topicToQuery = {
  // Cities
  'amsterdam': 'amsterdam canal houses',
  'athens': 'athens acropolis greece',
  'budapest': 'budapest parliament danube river',
  'florence': 'florence italy duomo tuscany',
  'istanbul': 'istanbul bosphorus turkey mosque',
  'munich': 'munich marienplatz bavaria',
  'santorini': 'santorini white houses blue dome greece',
  'booking-genius': 'hotel deal booking laptop',
  'carry-on-liquids': 'airport security liquids bag 100ml',
  'bali': 'bali rice terraces ubud',
  'bangkok': 'bangkok temple skyline',
  'barcelona': 'barcelona sagrada familia',
  'berlin': 'berlin brandenburg gate',
  'bogota': 'bogota colombia',
  'buenos-aires': 'buenos aires colorful houses',
  'cancun': 'cancun beach turquoise water',
  'cape-town': 'cape town table mountain',
  'cartagena': 'cartagena colombia colorful',
  'cusco': 'cusco peru plaza',
  'edinburgh': 'edinburgh castle scotland',
  'hanoi': 'hanoi old quarter vietnam',
  'hong-kong': 'hong kong skyline',
  'las-vegas': 'las vegas strip neon',
  'lima': 'lima peru pacific coast',
  'lisbon': 'lisbon yellow tram portugal',
  'london': 'london big ben thames',
  'los-angeles-city': 'los angeles palm trees',
  'madrid': 'madrid plaza mayor',
  'marrakech': 'marrakech morocco medina',
  'marseille': 'marseille old port',
  'medellin': 'medellin colombia',
  'mendoza': 'mendoza vineyards andes',
  'mexico-city': 'mexico city zocalo',
  'miami': 'miami beach art deco',
  'new-orleans': 'new orleans french quarter',
  'new-york': 'new york skyline manhattan',
  'paris': 'paris eiffel tower',
  'porto': 'porto portugal douro river',
  'prague': 'prague old town charles bridge',
  'rio-de-janeiro': 'rio de janeiro christ redeemer',
  'rome': 'rome colosseum',
  'sao-paulo': 'sao paulo skyline brazil',
  'warsaw': 'warsaw old town poland',
  'mykonos': 'mykonos windmills greece white',
  'san-francisco': 'san francisco golden gate',
  'seoul': 'seoul south korea',
  'seville': 'seville spain plaza',
  'singapore': 'singapore marina bay sands',
  'tokyo': 'tokyo neon street',
  'tulum': 'tulum mayan ruins beach',
  'vienna': 'vienna austria',

  // Topic-specific
  'tokyo-food': 'tokyo ramen sushi food',
  'ferrari-museum': 'ferrari sports car red',
  'puglia': 'puglia trulli alberobello',
  'albania-coast': 'albania ksamil beach',
  'faroe-islands': 'faroe islands cliffs',
  'iceland': 'iceland waterfall aurora',
  'patagonia': 'patagonia mountains torres del paine',
  'zanzibar': 'zanzibar stone town',
  'slovenia': 'slovenia bled lake',
  'santiago-de-compostela': 'santiago de compostela cathedral',
  'northern-lights': 'northern lights aurora borealis',
  'europe-hidden': 'europe hidden alpine village',
  'costa-rica': 'costa rica rainforest beach',
  'costa-rica-surf': 'costa rica surfing waves',

  // Travel topics
  'flights-cheap': 'airplane window clouds',
  'flights-booking': 'flight ticket calendar',
  'world-map': 'world map travel pin',
  'flight-ticket': 'boarding pass passport',
  'business-class': 'business class airplane seat',
  'airport-lounge': 'airport lounge premium',
  'airport': 'airport terminal travelers',
  'jet-lag': 'sleeping airplane window',
  'stopover': 'airport layover transfer',
  'ai-travel': 'laptop travel map',
  'ai-vs-agent': 'travel agent computer',
  'ai-tools': 'smartphone travel apps',
  'ai-comparison': 'computer screen comparison',
  'travel-planning': 'travel planning notebook map',
  'travel-journal': 'travel notebook journal pen',
  'hotel-booking': 'hotel reception lobby',
  'apartment-vs-hotel': 'modern apartment interior',
  'rental-car': 'rental car keys road',
  'rental-car-keys': 'car keys hand',
  'car-keys-money': 'car money savings',
  'travel-insurance': 'travel insurance documents',
  'cyber-security': 'laptop security travel',
  'travel-apps': 'smartphone travel app',
  'train-europe': 'european train alps scenic',
  'night-train': 'sleeper train cabin night',
  'train-station': 'train station platform europe',
  'road-trip': 'road trip mountain highway',
  'cruise-port': 'cruise ship port mediterranean',
  'carry-on-bag': 'carry on luggage suitcase',
  'capsule-wardrobe': 'minimalist clothes folded suitcase',
  'powerbank': 'phone charging cable airport',
  'forest-airplane': 'green forest aerial view',
  'reusable-bottle': 'reusable water bottle nature',
  'slow-travel': 'slow travel hammock',
  'workation': 'digital nomad laptop cafe remote work',
  'sabbatical': 'sabbatical mountain hiking',
  'solo-female-travel': 'woman solo traveler backpack',
  'travel-with-dog': 'dog travel adventure',
  'baby-travel': 'baby airplane travel',
  'boutique-hotel': 'boutique hotel room interior',
  'morocco-riad': 'morocco riad courtyard',
  // New topics 2026-05-09
  'greek-islands': 'greek islands white houses blue dome',
  'thailand': 'thailand temple bangkok golden',
  'dubai': 'dubai skyline burj khalifa',
  'hotel-upgrade': 'luxury hotel suite interior upgrade',
  'family-vacation': 'family travel beach children happy',
  'budget-travel': 'budget backpacker travel hostel',
  'autumn-travel': 'autumn fall foliage travel landscape',
  'maldives': 'maldives overwater bungalow turquoise',
  'luxury-travel': 'luxury hotel infinity pool ocean',
  'japan-kyoto': 'kyoto japan bamboo geisha temple',
  // New city topics for Where to Stay batch 3
  'antalya': 'antalya turkey old town harbor turquoise',
  'phuket': 'phuket thailand beach big buddha temple',
  'taipei': 'taipei taiwan 101 skyline night',
  'venice': 'venice italy canal gondola sunset',
  'dublin': 'dublin ireland temple bar colorful',
  'doha': 'doha qatar skyline corniche tower',
  'abu-dhabi': 'abu dhabi grand mosque white dome',
  'ho-chi-minh': 'ho chi minh city vietnam motorbike street',
  'toronto': 'toronto canada cn tower lake ontario',
  'stockholm': 'stockholm sweden gamla stan old town',
  'havana': 'havana cuba colorful colonial cars',
  'vancouver': 'vancouver canada mountains ocean harbour',
  'chicago': 'chicago skyline lake michigan architecture',
  // New city topics for Where to Stay batch 2
  'kuala-lumpur': 'kuala lumpur petronas towers skyline night',
  'osaka': 'osaka japan dotonbori neon reflections',
  'milan': 'milan italy cathedral duomo piazza',
  'sydney': 'sydney opera house harbour bridge australia',
  'copenhagen': 'copenhagen nyhavn colorful canal denmark',
  'kyoto': 'kyoto japan temple bamboo garden',
  'tbilisi': 'tbilisi georgia old town church sulfur',
  'valencia': 'valencia spain city arts sciences',
  // New topic articles (2026-05-09)
  'miles-points': 'travel credit card miles reward passport',
  'new-zealand': 'new zealand fiordland mountains fjord',
  'scotland': 'scotland highlands castle loch misty',
  'vietnam': 'vietnam halong bay karst limestone boat',
  'croatia-islands': 'adriatic sea island sailing mediterranean',
  'travel-photography': 'camera photographer nature landscape travel',
  'peru': 'peru machu picchu inca ruins clouds',
  'senior-travel': 'mature couple travel adventure smile',
  'ski-resort': 'ski resort alpine snow winter mountain',
  // Missing top cities batch (2026-05-09)
  'mumbai': 'mumbai india gateway of india skyline',
  'delhi': 'india city architecture colorful streets',
  'goa': 'goa india beach palm tropical turquoise',
  'auckland': 'auckland new zealand harbour skyline bridge',
  'santiago': 'santiago chile andes mountains skyline',
  'sao-paulo': 'sao paulo brazil city skyline aerial',
  'playa-del-carmen': 'caribbean beach mexico turquoise water palm',
  'puerto-vallarta': 'mexico pacific coast beach resort tropical',
  'oaxaca': 'oaxaca mexico colonial architecture church zocalo',
  'brussels': 'belgium capital city architecture street',
  'zurich': 'zurich switzerland lake old town river',
  'oslo': 'oslo norway opera house fjord waterfront',
  'warsaw': 'warsaw poland old town market square castle',
  'mykonos': 'greece island white buildings mediterranean sea',
  'johannesburg': 'south africa city modern skyline urban',
  // Replacement batch (2026-05-09)
  'dubrovnik': 'dubrovnik croatia old town adriatic walls',
  'reykjavik': 'reykjavik iceland colorful houses hallgrimskirkja',
  'krakow': 'krakow poland old town main market square',
  'valletta': 'valletta malta grand harbour baroque architecture',
  'chiang-mai': 'chiang mai thailand temple wat',
  'nairobi': 'nairobi kenya skyline africa city modern',
  // Batch 2026-05-11
  'tallinn': 'tallinn estonia old town medieval tower',
  'riga': 'riga latvia old town medieval',
  'route-66': 'route 66 usa road desert highway',
  'nice': 'nice france promenade des anglais mediterranean',
  'bologna': 'bologna italy two towers portico medieval',
  'bali-lombok': 'bali indonesia tropical beach volcano green',
  // Batch 2026-05-10
  'neapel': 'naples italy bay vesuvius waterfront',
  'malaga': 'malaga spain mediterranean harbor old city',
  'melbourne': 'melbourne australia city skyline flinders street',
  'jaipur': 'jaipur india pink city palace rajasthan',
  'washington-dc': 'washington dc capitol monument national mall',
  'reisekreditkarte': 'travel credit card passport airplane reward',
  'fruehbucher-last-minute': 'airport departure board flight booking',
  'hostel': 'hostel dorm bunk bed travelers backpacker',
  'geld-ausland': 'money foreign currency travel cash cards',
  'familienurlaub': 'family vacation beach kids summer travel happy',
  // Batch 2026-05-11 — Siem Reap + Sailing + Hiking
  'siem-reap': 'siem reap angkor wat temple cambodia',
  'sailing': 'sailing boat mediterranean sea yacht',
  'hiking-trails': 'long distance hiking trail mountain wilderness',
  // Batch 2026-05-11 — Colombo + Tipping + Winter Sun
  'colombo': 'colombo sri lanka galle face green skyline',
  'tipping-worldwide': 'money tip wallet travel global',
  'winter-sun': 'winter sun beach tropical warm january',
  // Batch 2026-05-11 — agents 3-6, 8-9
  'salzburg': 'salzburg austria old town castle fortress river',
  'split': 'split croatia adriatic coast harbor',
  'southeast-asia-budget': 'southeast asia backpacker travel budget hostel',
  'tenerife': 'tenerife canary islands teide volcano coast beach',
  'boston': 'boston massachusetts harbor skyline faneuil hall',
  'east-africa-safari': 'east africa safari savanna wildlife lion kenya',
  'seattle': 'seattle washington space needle skyline waterfront',
  'nashville': 'nashville tennessee broadway honky tonk downtown',
  'digital-nomad-visa': 'digital nomad laptop passport travel remote work',
  'penang': 'penang malaysia george town street art heritage',
  'europe-beaches': 'europe mediterranean beach crystal clear water sand',
  'wellness-spa': 'spa wellness retreat pool relax thermal',
  'brisbane': 'brisbane australia story bridge river skyline',
  'food-travel': 'food market street food local cuisine travel',
  'travel-mistakes': 'travel mistake luggage airport stress',
  'cairo': 'cairo egypt pyramids giza sphinx desert',
  'hotel-categories': 'hotel lobby luxury boutique rating reception',
  'teen-travel': 'family travel teenagers adventure fun vacation',
  // New 2026-05-11 batch
  'cruise-beginner': 'cruise ship ocean deck vacation sunny',
  'house-swap': 'house keys exchange home travel swap',
  'visa-on-arrival': 'passport stamp arrival airport border',
  // Batch 2026-05-11 — Bilbao + Granada + Algarve
  'bilbao': 'bilbao guggenheim museum spain basque',
  'granada': 'granada spain alhambra moorish palace',
  'algarve': 'algarve portugal cliffs golden coast ocean',
  // Batch 2026-05-11 — Kotor + Bucharest + Winter Europe
  'kotor': 'mediterranean old town bay fortress walls',
  'bucharest': 'eastern europe city palace boulevard architecture',
  'winter-europe': 'europe christmas market winter snow lights',
  // Batch 2026-05-11 — agents 1, 3, 5, 6, 7, 8, 10
  'bordeaux': 'bordeaux france wine city river gironde',
  'palma-de-mallorca': 'palma mallorca cathedral sea blue',
  'campervan-europe': 'campervan road europe nature motorhome',
  'lanzarote': 'lanzarote canary islands volcanic landscape ocean',
  'ljubljana': 'ljubljana slovenia castle river old town',
  'diving-snorkeling': 'diving coral reef tropical fish underwater',
  'vilnius': 'vilnius lithuania old town baroque church',
  'montreal': 'canada city old port river architecture',
  'switzerland': 'switzerland alps mountains lake jungfrau',
  'guadalajara': 'guadalajara mexico cathedral plaza historic',
  'kathmandu': 'nepal himalaya temple mountain asia',
  'city-cards': 'tourist city card museum pass travel',
  'hoi-an': 'hoi an vietnam ancient town lanterns',
  'queenstown': 'queenstown new zealand lake remarkables mountains',
  'airport-transfer': 'airport terminal taxi bus transfer travelers',
  'funchal': 'madeira portugal island flowers colorful',
  'yoga-retreat': 'yoga retreat meditation sunrise mountains nature',
  'surf-beginner': 'surfing beginner lesson wave ocean beach',
  'caribbean-islands': 'caribbean islands turquoise water beach tropical',
  'package-tour-vs-independent': 'travel planning map group tour independent',
  'best-beaches-world': 'tropical beach paradise crystal clear water white sand',
};
