// Maps each blog slug to a topic key + Unsplash search term.
// All slugs sharing a topicKey use the SAME photo file (saves API calls + storage).
// Run via: node scripts/download-photos.mjs

export const slugToTopic = {
  // ===== CITY GUIDES (3-4 slug variants per city, share photo) =====
  // Where to Stay - Europa
  'wo-uebernachten-amsterdam': 'amsterdam',
  'where-to-stay-amsterdam': 'amsterdam',
  'wo-uebernachten-athen': 'athens',
  'where-to-stay-athens': 'athens',
  'wo-uebernachten-barcelona': 'barcelona',
  'where-to-stay-barcelona': 'barcelona',
  'wo-uebernachten-berlin': 'berlin',
  'where-to-stay-berlin': 'berlin',
  'wo-uebernachten-edinburgh': 'edinburgh',
  'where-to-stay-edinburgh': 'edinburgh',
  'wo-uebernachten-lissabon': 'lisbon',
  'where-to-stay-lisbon': 'lisbon',
  'wo-uebernachten-london': 'london',
  'where-to-stay-london': 'london',
  'wo-uebernachten-madrid': 'madrid',
  'where-to-stay-madrid': 'madrid',
  'wo-uebernachten-marseille': 'marseille',
  'where-to-stay-marseille': 'marseille',
  'wo-uebernachten-paris': 'paris',
  'where-to-stay-paris': 'paris',
  'wo-uebernachten-prag': 'prague',
  'where-to-stay-prague': 'prague',
  'wo-uebernachten-rom': 'rome',
  'where-to-stay-rome': 'rome',
  'wo-uebernachten-sevilla': 'seville',
  'where-to-stay-seville': 'seville',
  'wo-uebernachten-budapest': 'budapest',
  'where-to-stay-budapest': 'budapest',
  'donde-alojarse-budapest': 'budapest',
  'wo-uebernachten-florenz': 'florence',
  'where-to-stay-florence': 'florence',
  'donde-alojarse-florencia': 'florence',
  'wo-uebernachten-istanbul': 'istanbul',
  'where-to-stay-istanbul': 'istanbul',
  'donde-alojarse-estambul': 'istanbul',
  'wo-uebernachten-muenchen': 'munich',
  'where-to-stay-munich': 'munich',
  'donde-alojarse-munich': 'munich',
  'wo-uebernachten-santorini': 'santorini',
  'where-to-stay-santorini': 'santorini',
  'donde-alojarse-santorini': 'santorini',
  'wo-uebernachten-wien': 'vienna',
  'where-to-stay-vienna': 'vienna',
  // Where to Stay - LATAM (DE+EN+ES)
  'wo-uebernachten-bogota': 'bogota',
  'where-to-stay-bogota': 'bogota',
  'donde-alojarse-bogota': 'bogota',
  'wo-uebernachten-buenos-aires': 'buenos-aires',
  'where-to-stay-buenos-aires': 'buenos-aires',
  'donde-alojarse-buenos-aires': 'buenos-aires',
  'wo-uebernachten-cancun': 'cancun',
  'where-to-stay-cancun': 'cancun',
  'donde-alojarse-cancun': 'cancun',
  'wo-uebernachten-cartagena': 'cartagena',
  'where-to-stay-cartagena': 'cartagena',
  'donde-alojarse-cartagena': 'cartagena',
  'wo-uebernachten-cusco': 'cusco',
  'where-to-stay-cusco': 'cusco',
  'donde-alojarse-cusco': 'cusco',
  'wo-uebernachten-lima': 'lima',
  'where-to-stay-lima': 'lima',
  'donde-alojarse-lima': 'lima',
  'wo-uebernachten-medellin': 'medellin',
  'where-to-stay-medellin': 'medellin',
  'donde-alojarse-medellin': 'medellin',
  'wo-uebernachten-mendoza': 'mendoza',
  'where-to-stay-mendoza': 'mendoza',
  'donde-alojarse-mendoza': 'mendoza',
  'wo-uebernachten-mexico-city': 'mexico-city',
  'where-to-stay-mexico-city': 'mexico-city',
  'donde-alojarse-ciudad-de-mexico': 'mexico-city',
  'wo-uebernachten-miami': 'miami',
  'where-to-stay-miami': 'miami',
  'donde-alojarse-miami': 'miami',
  'wo-uebernachten-rio-de-janeiro': 'rio-de-janeiro',
  'where-to-stay-rio-de-janeiro': 'rio-de-janeiro',
  'donde-alojarse-rio-de-janeiro': 'rio-de-janeiro',
  'wo-uebernachten-tulum': 'tulum',
  'where-to-stay-tulum': 'tulum',
  'donde-alojarse-tulum': 'tulum',
  // Where to Stay - USA
  'wo-uebernachten-las-vegas': 'las-vegas',
  'where-to-stay-las-vegas': 'las-vegas',
  'wo-uebernachten-los-angeles': 'los-angeles-city',
  'where-to-stay-los-angeles': 'los-angeles-city',
  'los-angeles': 'los-angeles-city',
  'wo-uebernachten-new-orleans': 'new-orleans',
  'where-to-stay-new-orleans': 'new-orleans',
  'wo-uebernachten-new-york': 'new-york',
  'where-to-stay-new-york': 'new-york',
  'wo-uebernachten-san-francisco': 'san-francisco',
  'where-to-stay-san-francisco': 'san-francisco',
  // Where to Stay - Asia
  'wo-uebernachten-bali': 'bali',
  'where-to-stay-bali': 'bali',
  'wo-uebernachten-bangkok': 'bangkok',
  'where-to-stay-bangkok': 'bangkok',
  'wo-uebernachten-hanoi': 'hanoi',
  'where-to-stay-hanoi': 'hanoi',
  'wo-uebernachten-hongkong': 'hong-kong',
  'where-to-stay-hong-kong': 'hong-kong',
  'wo-uebernachten-seoul': 'seoul',
  'where-to-stay-seoul': 'seoul',
  'wo-uebernachten-singapur': 'singapore',
  'where-to-stay-singapore': 'singapore',
  'wo-uebernachten-tokio': 'tokyo',
  'where-to-stay-tokyo': 'tokyo',
  // Where to Stay - Africa
  'wo-uebernachten-cape-town': 'cape-town',
  'where-to-stay-cape-town': 'cape-town',
  'wo-uebernachten-marrakesch': 'marrakech',
  'where-to-stay-marrakech': 'marrakech',

  // ===== TOPIC ARTICLES =====
  // Cities (non-where-to-stay)
  '48-hours-rome': 'rome',
  '48-stunden-rom': 'rome',
  'madrid-24-hours': 'madrid',
  'madrid-24-stunden': 'madrid',
  'tokio-foodie-reise': 'tokyo-food',
  'tokyo-foodie-trip': 'tokyo-food',
  'lisbon-beyond-the-tourist-trail': 'lisbon',
  'lissabon-abseits-der-touristenpfade': 'lisbon',
  'porto-die-unterschaetzte-schwester': 'porto',
  'porto-lisbons-underrated-sister': 'porto',
  'modena-ferrari-museum': 'ferrari-museum',
  'apulien-sueditalien-guide': 'puglia',
  'puglia-southern-italy-guide': 'puglia',

  // Off the Map / Hidden Gems
  'albania-riviera-hidden-coast': 'albania-coast',
  'albanien-riviera-geheimtipp': 'albania-coast',
  'faeroeer-inseln-guide': 'faroe-islands',
  'faroe-islands-guide': 'faroe-islands',
  'iceland-travel-guide': 'iceland',
  'island-reiseguide': 'iceland',
  'patagonia-3-week-route': 'patagonia',
  'patagonien-3-wochen-route': 'patagonia',
  'sansibar-stone-town-guide': 'zanzibar',
  'zanzibar-stone-town-guide': 'zanzibar',
  'slovenia-green-secret-2026': 'slovenia',
  'slowenien-geheimnis-2026': 'slovenia',
  'santiago-de-compostela': 'santiago-de-compostela',
  'nordlichter-2026-wo-wann-wie': 'northern-lights',
  'northern-lights-2026-where-when-how': 'northern-lights',
  'geheimtipps-europa': 'europe-hidden',
  'hidden-gems-europe': 'europe-hidden',

  // Costa Rica
  'costa-rica-rundreise-route': 'costa-rica',
  'costa-rica-road-trip-route': 'costa-rica',
  'costa-rica-surfen': 'costa-rica-surf',
  'costa-rica-surfing': 'costa-rica-surf',

  // Travel Tips - Flights
  'guenstig-fliegen-tipps': 'flights-cheap',
  'cheap-flights-tips': 'flights-cheap',
  'wann-fluege-buchen': 'flights-booking',
  'when-to-book-flights': 'flights-booking',
  'open-jaw-tickets-reise-hack': 'world-map',
  'open-jaw-tickets-travel-hack': 'world-map',
  'hidden-city-ticketing-erklaert': 'flight-ticket',
  'hidden-city-ticketing-explained': 'flight-ticket',
  'business-class': 'business-class',
  'business-class-worth-it': 'business-class',
  'business-class-ohne-meilen': 'business-class',
  'business-class-without-miles': 'business-class',
  'lounge-zugang-ohne-business-ticket': 'airport-lounge',
  'lounge-access-without-business-ticket': 'airport-lounge',
  'airport-hacks': 'airport',
  'jetlag-schnell-ueberwinden': 'jet-lag',
  'jet-lag-fast-recovery': 'jet-lag',
  'stopover-tourismus-guide': 'stopover',
  'stopover-tourism-guide': 'stopover',

  // AI & Travel
  'ki-veraendert-reiseplanung': 'ai-travel',
  'ai-changing-travel-planning': 'ai-travel',
  'ki-reiseplaner-vs-reisebuero': 'ai-vs-agent',
  'ai-trip-planner-vs-travel-agent': 'ai-vs-agent',
  'ki-tools-reise-vergleich': 'ai-tools',
  'ai-tools-travel-comparison': 'ai-tools',
  'ki-vergleich-reiseplanung-2026': 'ai-comparison',
  'ai-comparison-trip-planning-2026': 'ai-comparison',
  'was-ist-zercy': 'travel-planning',
  'what-is-zercy': 'travel-planning',
  'zercy-logbook': 'travel-journal',

  // Smart Travel
  'booking-vs-direkt-buchen': 'hotel-booking',
  'booking-vs-direct-hotel-booking': 'hotel-booking',
  'airbnb-vs-hotel-vergleich': 'apartment-vs-hotel',
  'airbnb-vs-hotel-comparison': 'apartment-vs-hotel',
  'booking-genius-programm-lohnt-es-sich': 'booking-genius',
  'booking-genius-program-worth-it': 'booking-genius',
  'booking-genius-vale-la-pena': 'booking-genius',
  'booking-apartments-vs-airbnb': 'apartment-vs-hotel',
  'apartamento-vs-hotel-cual-elegir': 'apartment-vs-hotel',
  'mietwagen-check': 'rental-car',
  'rental-car-checklist': 'rental-car',
  'mietwagen-versteckte-kosten-vermeiden': 'rental-car-keys',
  'rental-car-hidden-costs-avoid': 'rental-car-keys',
  'mietwagen-consolidator-guenstiger-fahren': 'car-keys-money',
  'rental-consolidators-save-money': 'car-keys-money',
  'reiseversicherung-was-lohnt-sich': 'travel-insurance',
  'travel-insurance-worth-it-2026': 'travel-insurance',
  'cyber-sicherheit-reisen': 'cyber-security',
  'cyber-security-travel-2026': 'cyber-security',
  'beste-travel-apps-2026': 'travel-apps',
  'best-travel-apps-2026': 'travel-apps',

  // On the Move
  'zugreisen-europa': 'train-europe',
  'train-travel-europe': 'train-europe',
  'nachtzuege-europa-2026': 'night-train',
  'night-trains-europe-2026': 'night-train',
  'bahn-vs-flieger-europa-2026': 'train-station',
  'train-vs-plane-europe-2026': 'train-station',
  'roadtrip-etappen-planung': 'road-trip',
  'road-trip-stages-planning': 'road-trip',
  'kreuzfahrt-staedte-verlaengern': 'cruise-port',
  'cruise-extend-port-cities': 'cruise-port',

  // Carry-On Only
  'nur-handgepaeck': 'carry-on-bag',
  'carry-on-only': 'carry-on-bag',
  'capsule-wardrobe-handgepaeck': 'capsule-wardrobe',
  'capsule-wardrobe-carry-on': 'capsule-wardrobe',
  'powerbank-regeln-handgepaeck-2026': 'powerbank',
  'powerbank-rules-carry-on-2026': 'powerbank',
  'handgepaeck-fluessigkeiten-regeln-2026': 'carry-on-liquids',
  'carry-on-liquids-rules-2026': 'carry-on-liquids',
  'liquidos-equipaje-mano-2026': 'carry-on-liquids',

  // Travel Green
  'co2-kompensation-fliegen': 'forest-airplane',
  'flight-carbon-offsets-truth': 'forest-airplane',
  'plastik-frei-reisen-tipps': 'reusable-bottle',
  'plastic-free-travel-tips': 'reusable-bottle',
  'slow-travel-bedeutet-was': 'slow-travel',
  'slow-travel-what-it-really-means': 'slow-travel',

  // Lifestyle / Special
  'workation-steuern-2026': 'workation',
  'workation-tax-rules-2026': 'workation',
  'sabbatical-planen-guide': 'sabbatical',
  'sabbatical-planning-guide': 'sabbatical',
  'solo-reisen-frauen-sicher': 'solo-female-travel',
  'solo-travel-women-safe-countries': 'solo-female-travel',
  'mit-hund-europa-reisen': 'travel-with-dog',
  'traveling-with-dog-europe': 'travel-with-dog',
  'reisen-mit-baby-erste-fluege': 'baby-travel',
  'traveling-with-baby-first-flights': 'baby-travel',

  // Hotels (general)
  'boutique-hotels': 'boutique-hotel',
  'riads-marokko-guide': 'morocco-riad',
  'morocco-riads-guide': 'morocco-riad',
};

// Topic key -> Unsplash search query (used when downloading)
export const topicToQuery = {
  // Cities
  'amsterdam': 'amsterdam canal houses',
  'athens': 'athens acropolis greece',
  'budapest': 'budapest parliament danube river',
  'florence': 'florence italy duomo tuscany',
  'istanbul': 'istanbul bosphorus turkey mosque',
  'munich': 'munich marienplatz bavaria',
  'santorini': 'santorini white houses blue dome greece',
  'booking-genius': 'hotel deal booking laptop',
  'carry-on-liquids': 'airport security liquids bag 100ml',
  'bali': 'bali rice terraces ubud',
  'bangkok': 'bangkok temple skyline',
  'barcelona': 'barcelona sagrada familia',
  'berlin': 'berlin brandenburg gate',
  'bogota': 'bogota colombia',
  'buenos-aires': 'buenos aires colorful houses',
  'cancun': 'cancun beach turquoise water',
  'cape-town': 'cape town table mountain',
  'cartagena': 'cartagena colombia colorful',
  'cusco': 'cusco peru plaza',
  'edinburgh': 'edinburgh castle scotland',
  'hanoi': 'hanoi old quarter vietnam',
  'hong-kong': 'hong kong skyline',
  'las-vegas': 'las vegas strip neon',
  'lima': 'lima peru pacific coast',
  'lisbon': 'lisbon yellow tram portugal',
  'london': 'london big ben thames',
  'los-angeles-city': 'los angeles palm trees',
  'madrid': 'madrid plaza mayor',
  'marrakech': 'marrakech morocco medina',
  'marseille': 'marseille old port',
  'medellin': 'medellin colombia',
  'mendoza': 'mendoza vineyards andes',
  'mexico-city': 'mexico city zocalo',
  'miami': 'miami beach art deco',
  'new-orleans': 'new orleans french quarter',
  'new-york': 'new york skyline manhattan',
  'paris': 'paris eiffel tower',
  'porto': 'porto portugal douro river',
  'prague': 'prague old town charles bridge',
  'rio-de-janeiro': 'rio de janeiro christ redeemer',
  'rome': 'rome colosseum',
  'san-francisco': 'san francisco golden gate',
  'seoul': 'seoul south korea',
  'seville': 'seville spain plaza',
  'singapore': 'singapore marina bay sands',
  'tokyo': 'tokyo neon street',
  'tulum': 'tulum mayan ruins beach',
  'vienna': 'vienna austria',

  // Topic-specific
  'tokyo-food': 'tokyo ramen sushi food',
  'ferrari-museum': 'ferrari sports car red',
  'puglia': 'puglia trulli alberobello',
  'albania-coast': 'albania ksamil beach',
  'faroe-islands': 'faroe islands cliffs',
  'iceland': 'iceland waterfall aurora',
  'patagonia': 'patagonia mountains torres del paine',
  'zanzibar': 'zanzibar stone town',
  'slovenia': 'slovenia bled lake',
  'santiago-de-compostela': 'santiago de compostela cathedral',
  'northern-lights': 'northern lights aurora borealis',
  'europe-hidden': 'europe hidden alpine village',
  'costa-rica': 'costa rica rainforest beach',
  'costa-rica-surf': 'costa rica surfing waves',

  // Travel topics
  'flights-cheap': 'airplane window clouds',
  'flights-booking': 'flight ticket calendar',
  'world-map': 'world map travel pin',
  'flight-ticket': 'boarding pass passport',
  'business-class': 'business class airplane seat',
  'airport-lounge': 'airport lounge premium',
  'airport': 'airport terminal travelers',
  'jet-lag': 'sleeping airplane window',
  'stopover': 'airport layover transfer',
  'ai-travel': 'laptop travel map',
  'ai-vs-agent': 'travel agent computer',
  'ai-tools': 'smartphone travel apps',
  'ai-comparison': 'computer screen comparison',
  'travel-planning': 'travel planning notebook map',
  'travel-journal': 'travel notebook journal pen',
  'hotel-booking': 'hotel reception lobby',
  'apartment-vs-hotel': 'modern apartment interior',
  'rental-car': 'rental car keys road',
  'rental-car-keys': 'car keys hand',
  'car-keys-money': 'car money savings',
  'travel-insurance': 'travel insurance documents',
  'cyber-security': 'laptop security travel',
  'travel-apps': 'smartphone travel app',
  'train-europe': 'european train alps scenic',
  'night-train': 'sleeper train cabin night',
  'train-station': 'train station platform europe',
  'road-trip': 'road trip mountain highway',
  'cruise-port': 'cruise ship port mediterranean',
  'carry-on-bag': 'carry on luggage suitcase',
  'capsule-wardrobe': 'minimalist clothes folded suitcase',
  'powerbank': 'phone charging cable airport',
  'forest-airplane': 'green forest aerial view',
  'reusable-bottle': 'reusable water bottle nature',
  'slow-travel': 'slow travel hammock',
  'workation': 'laptop beach workation',
  'sabbatical': 'sabbatical mountain hiking',
  'solo-female-travel': 'woman solo traveler backpack',
  'travel-with-dog': 'dog travel adventure',
  'baby-travel': 'baby airplane travel',
  'boutique-hotel': 'boutique hotel room interior',
  'morocco-riad': 'morocco riad courtyard',
};
