// Maps each blog slug to a topic key + Unsplash search term.
// All slugs sharing a topicKey use the SAME photo file (saves API calls + storage).
// Run via: node scripts/download-photos.mjs

export const slugToTopic = {
  // ===== CITY GUIDES (3-4 slug variants per city, share photo) =====
  // Where to Stay - Europa
  'wo-uebernachten-amsterdam': 'amsterdam',
  'where-to-stay-amsterdam': 'amsterdam',
  'wo-uebernachten-athen': 'athens',
  'where-to-stay-athens': 'athens',
  'wo-uebernachten-barcelona': 'barcelona',
  'where-to-stay-barcelona': 'barcelona',
  'wo-uebernachten-berlin': 'berlin',
  'where-to-stay-berlin': 'berlin',
  'wo-uebernachten-edinburgh': 'edinburgh',
  'where-to-stay-edinburgh': 'edinburgh',
  'wo-uebernachten-lissabon': 'lisbon',
  'where-to-stay-lisbon': 'lisbon',
  'wo-uebernachten-london': 'london',
  'where-to-stay-london': 'london',
  'wo-uebernachten-madrid': 'madrid',
  'where-to-stay-madrid': 'madrid',
  'wo-uebernachten-marseille': 'marseille',
  'where-to-stay-marseille': 'marseille',
  'wo-uebernachten-paris': 'paris',
  'where-to-stay-paris': 'paris',
  'wo-uebernachten-prag': 'prague',
  'where-to-stay-prague': 'prague',
  'wo-uebernachten-rom': 'rome',
  'where-to-stay-rome': 'rome',
  'wo-uebernachten-sevilla': 'seville',
  'where-to-stay-seville': 'seville',
  'wo-uebernachten-budapest': 'budapest',
  'where-to-stay-budapest': 'budapest',
  'donde-alojarse-budapest': 'budapest',
  'wo-uebernachten-florenz': 'florence',
  'where-to-stay-florence': 'florence',
  'donde-alojarse-florencia': 'florence',
  'wo-uebernachten-istanbul': 'istanbul',
  'where-to-stay-istanbul': 'istanbul',
  'donde-alojarse-estambul': 'istanbul',
  'wo-uebernachten-muenchen': 'munich',
  'where-to-stay-munich': 'munich',
  'donde-alojarse-munich': 'munich',
  'wo-uebernachten-santorini': 'santorini',
  'where-to-stay-santorini': 'santorini',
  'donde-alojarse-santorini': 'santorini',
  'wo-uebernachten-wien': 'vienna',
  'where-to-stay-vienna': 'vienna',
  // Where to Stay - LATAM (DE+EN+ES)
  'wo-uebernachten-bogota': 'bogota',
  'where-to-stay-bogota': 'bogota',
  'donde-alojarse-bogota': 'bogota',
  'wo-uebernachten-buenos-aires': 'buenos-aires',
  'where-to-stay-buenos-aires': 'buenos-aires',
  'donde-alojarse-buenos-aires': 'buenos-aires',
  'wo-uebernachten-cancun': 'cancun',
  'where-to-stay-cancun': 'cancun',
  'donde-alojarse-cancun': 'cancun',
  'wo-uebernachten-cartagena': 'cartagena',
  'where-to-stay-cartagena': 'cartagena',
  'donde-alojarse-cartagena': 'cartagena',
  'wo-uebernachten-cusco': 'cusco',
  'where-to-stay-cusco': 'cusco',
  'donde-alojarse-cusco': 'cusco',
  'wo-uebernachten-lima': 'lima',
  'where-to-stay-lima': 'lima',
  'donde-alojarse-lima': 'lima',
  'wo-uebernachten-medellin': 'medellin',
  'where-to-stay-medellin': 'medellin',
  'donde-alojarse-medellin': 'medellin',
  'wo-uebernachten-mendoza': 'mendoza',
  'where-to-stay-mendoza': 'mendoza',
  'donde-alojarse-mendoza': 'mendoza',
  'wo-uebernachten-mexico-city': 'mexico-city',
  'where-to-stay-mexico-city': 'mexico-city',
  'donde-alojarse-ciudad-de-mexico': 'mexico-city',
  'wo-uebernachten-miami': 'miami',
  'where-to-stay-miami': 'miami',
  'donde-alojarse-miami': 'miami',
  'wo-uebernachten-rio-de-janeiro': 'rio-de-janeiro',
  'where-to-stay-rio-de-janeiro': 'rio-de-janeiro',
  'donde-alojarse-rio-de-janeiro': 'rio-de-janeiro',
  'wo-uebernachten-tulum': 'tulum',
  'where-to-stay-tulum': 'tulum',
  'donde-alojarse-tulum': 'tulum',
  // Where to Stay - USA
  'wo-uebernachten-las-vegas': 'las-vegas',
  'where-to-stay-las-vegas': 'las-vegas',
  'wo-uebernachten-los-angeles': 'los-angeles-city',
  'where-to-stay-los-angeles': 'los-angeles-city',
  'los-angeles': 'los-angeles-city',
  'wo-uebernachten-new-orleans': 'new-orleans',
  'where-to-stay-new-orleans': 'new-orleans',
  'wo-uebernachten-new-york': 'new-york',
  'where-to-stay-new-york': 'new-york',
  'wo-uebernachten-san-francisco': 'san-francisco',
  'where-to-stay-san-francisco': 'san-francisco',
  // Where to Stay - Asia
  'wo-uebernachten-bali': 'bali',
  'where-to-stay-bali': 'bali',
  'wo-uebernachten-bangkok': 'bangkok',
  'where-to-stay-bangkok': 'bangkok',
  'wo-uebernachten-hanoi': 'hanoi',
  'where-to-stay-hanoi': 'hanoi',
  'wo-uebernachten-hongkong': 'hong-kong',
  'where-to-stay-hong-kong': 'hong-kong',
  'wo-uebernachten-seoul': 'seoul',
  'where-to-stay-seoul': 'seoul',
  'wo-uebernachten-singapur': 'singapore',
  'where-to-stay-singapore': 'singapore',
  'wo-uebernachten-tokio': 'tokyo',
  'where-to-stay-tokyo': 'tokyo',
  // Where to Stay - Africa
  'wo-uebernachten-cape-town': 'cape-town',
  'where-to-stay-cape-town': 'cape-town',
  'wo-uebernachten-marrakesch': 'marrakech',
  'where-to-stay-marrakech': 'marrakech',

  // ES Where-to-Stay (Steps 2+3, not yet in mapping)
  'donde-alojarse-berlin': 'berlin',
  'donde-alojarse-sevilla': 'seville',
  'donde-alojarse-marsella': 'marseille',
  'donde-alojarse-edimburgo': 'edinburgh',
  'donde-alojarse-ciudad-del-cabo': 'cape-town',
  'donde-alojarse-tokio': 'tokyo',
  'donde-alojarse-bangkok': 'bangkok',
  'donde-alojarse-seul': 'seoul',
  'donde-alojarse-hanoi': 'hanoi',
  'donde-alojarse-nueva-york': 'new-york',
  'donde-alojarse-san-francisco': 'san-francisco',
  'donde-alojarse-los-angeles': 'los-angeles-city',
  'donde-alojarse-las-vegas': 'las-vegas',
  'donde-alojarse-nueva-orleans': 'new-orleans',
  'donde-alojarse-hong-kong': 'hong-kong',
  'donde-alojarse-singapur': 'singapore',
  'donde-alojarse-bali': 'bali',
  'donde-alojarse-amsterdam': 'amsterdam',
  'donde-alojarse-atenas': 'athens',
  'donde-alojarse-barcelona': 'barcelona',
  'donde-alojarse-lisboa': 'lisbon',
  'donde-alojarse-madrid': 'madrid',
  'donde-alojarse-marrakech': 'marrakech',
  'donde-alojarse-paris': 'paris',
  'donde-alojarse-praga': 'prague',
  'donde-alojarse-roma': 'rome',
  'donde-alojarse-viena': 'vienna',
  'donde-alojarse-santorini': 'santorini',

  // ===== TOPIC ARTICLES =====
  // Cities (non-where-to-stay)
  '48-hours-rome': 'rome',
  '48-stunden-rom': 'rome',
  '48-horas-roma': 'rome',
  'madrid-24-hours': 'madrid',
  'madrid-24-stunden': 'madrid',
  'madrid-24-horas': 'madrid',
  'tokio-foodie-reise': 'tokyo-food',
  'tokyo-foodie-trip': 'tokyo-food',
  'tokio-viaje-gastronomico': 'tokyo-food',
  'lisbon-beyond-the-tourist-trail': 'lisbon',
  'lissabon-abseits-der-touristenpfade': 'lisbon',
  'lisboa-fuera-ruta-turistica': 'lisbon',
  'porto-die-unterschaetzte-schwester': 'porto',
  'porto-lisbons-underrated-sister': 'porto',
  'oporto-hermana-subestimada': 'porto',
  'modena-ferrari-museum': 'ferrari-museum',
  'modena-museo-ferrari': 'ferrari-museum',
  'apulien-sueditalien-guide': 'puglia',
  'puglia-southern-italy-guide': 'puglia',
  'apulia-sur-italia-guia': 'puglia',
  'santiago-de-compostela': 'santiago-de-compostela',
  'santiago-de-compostela-ruta': 'santiago-de-compostela',

  // Off the Map / Hidden Gems
  'albania-riviera-hidden-coast': 'albania-coast',
  'albanien-riviera-geheimtipp': 'albania-coast',
  'albania-riviera-escondida': 'albania-coast',
  'faeroeer-inseln-guide': 'faroe-islands',
  'faroe-islands-guide': 'faroe-islands',
  'islas-feroe-guia': 'faroe-islands',
  'iceland-travel-guide': 'iceland',
  'island-reiseguide': 'iceland',
  'islandia-guia-viaje': 'iceland',
  'patagonia-3-week-route': 'patagonia',
  'patagonien-3-wochen-route': 'patagonia',
  'patagonia-3-semanas-ruta': 'patagonia',
  'sansibar-stone-town-guide': 'zanzibar',
  'zanzibar-stone-town-guide': 'zanzibar',
  'zanzibar-stone-town-guia': 'zanzibar',
  'slovenia-green-secret-2026': 'slovenia',
  'slowenien-geheimnis-2026': 'slovenia',
  'eslovenia-secreto-verde-2026': 'slovenia',
  'nordlichter-2026-wo-wann-wie': 'northern-lights',
  'northern-lights-2026-where-when-how': 'northern-lights',
  'auroras-boreales-2026': 'northern-lights',
  'geheimtipps-europa': 'europe-hidden',
  'hidden-gems-europe': 'europe-hidden',
  'joyas-ocultas-europa': 'europe-hidden',

  // Costa Rica
  'costa-rica-rundreise-route': 'costa-rica',
  'costa-rica-road-trip-route': 'costa-rica',
  'costa-rica-ruta-completa': 'costa-rica',
  'costa-rica-surfen': 'costa-rica-surf',
  'costa-rica-surfing': 'costa-rica-surf',
  'costa-rica-surf': 'costa-rica-surf',

  // Travel Tips - Flights
  'guenstig-fliegen-tipps': 'flights-cheap',
  'cheap-flights-tips': 'flights-cheap',
  'consejos-vuelos-baratos': 'flights-cheap',
  'wann-fluege-buchen': 'flights-booking',
  'when-to-book-flights': 'flights-booking',
  'cuando-reservar-vuelos': 'flights-booking',
  'open-jaw-tickets-reise-hack': 'world-map',
  'open-jaw-tickets-travel-hack': 'world-map',
  'open-jaw-tickets-truco-viaje': 'world-map',
  'hidden-city-ticketing-erklaert': 'flight-ticket',
  'hidden-city-ticketing-explained': 'flight-ticket',
  'hidden-city-ticketing-explicado': 'flight-ticket',
  'business-class': 'business-class',
  'business-class-worth-it': 'business-class',
  'business-class-vale-la-pena': 'business-class',
  'business-class-ohne-meilen': 'business-class',
  'business-class-without-miles': 'business-class',
  'business-class-sin-millas': 'business-class',
  'lounge-zugang-ohne-business-ticket': 'airport-lounge',
  'lounge-access-without-business-ticket': 'airport-lounge',
  'acceso-sala-vip-sin-business': 'airport-lounge',
  'airport-hacks': 'airport',
  'trucos-aeropuerto': 'airport',
  'jetlag-schnell-ueberwinden': 'jet-lag',
  'jet-lag-fast-recovery': 'jet-lag',
  'superar-jetlag-rapido': 'jet-lag',
  'stopover-tourismus-guide': 'stopover',
  'stopover-tourism-guide': 'stopover',
  'guia-stopover-turismo': 'stopover',
  'bahn-vs-flieger-europa-2026': 'train-station',
  'train-vs-plane-europe-2026': 'train-station',
  'tren-vs-avion-europa-2026': 'train-station',
  'normas-powerbank-equipaje-mano': 'powerbank',

  // AI & Travel
  'ki-veraendert-reiseplanung': 'ai-travel',
  'ai-changing-travel-planning': 'ai-travel',
  'ia-cambia-planificacion-viajes': 'ai-travel',
  'ki-reiseplaner-vs-reisebuero': 'ai-vs-agent',
  'ai-trip-planner-vs-travel-agent': 'ai-vs-agent',
  'planificador-ia-vs-agencia-viajes': 'ai-vs-agent',
  'ki-tools-reise-vergleich': 'ai-tools',
  'ai-tools-travel-comparison': 'ai-tools',
  'herramientas-ia-comparativa-viajes': 'ai-tools',
  'ki-vergleich-reiseplanung-2026': 'ai-comparison',
  'ai-comparison-trip-planning-2026': 'ai-comparison',
  'ia-comparativa-planificacion-2026': 'ai-comparison',
  'was-ist-zercy': 'travel-planning',
  'what-is-zercy': 'travel-planning',
  'que-es-zercy': 'travel-planning',
  'zercy-logbook': 'travel-journal',
  'zercy-logbook-que-es': 'travel-journal',

  // Smart Travel
  'booking-vs-direkt-buchen': 'hotel-booking',
  'booking-vs-direct-hotel-booking': 'hotel-booking',
  'reservar-online-o-directo': 'hotel-booking',
  'airbnb-vs-hotel-vergleich': 'apartment-vs-hotel',
  'airbnb-vs-hotel-comparison': 'apartment-vs-hotel',
  'airbnb-vs-hotel-comparacion': 'apartment-vs-hotel',
  'booking-genius-programm-lohnt-es-sich': 'booking-genius',
  'booking-genius-program-worth-it': 'booking-genius',
  'booking-genius-vale-la-pena': 'booking-genius',
  'booking-apartments-vs-airbnb': 'apartment-vs-hotel',
  'apartamento-vs-hotel-cual-elegir': 'apartment-vs-hotel',
  'mietwagen-check': 'rental-car',
  'rental-car-checklist': 'rental-car',
  'checklist-alquiler-coche': 'rental-car',
  'mietwagen-versteckte-kosten-vermeiden': 'rental-car-keys',
  'rental-car-hidden-costs-avoid': 'rental-car-keys',
  'costes-ocultos-alquiler-coche': 'rental-car-keys',
  'mietwagen-consolidator-guenstiger-fahren': 'car-keys-money',
  'rental-consolidators-save-money': 'car-keys-money',
  'consolidadores-alquiler-ahorrar': 'car-keys-money',
  'reiseversicherung-was-lohnt-sich': 'travel-insurance',
  'travel-insurance-worth-it-2026': 'travel-insurance',
  'seguro-viaje-vale-la-pena': 'travel-insurance',
  'cyber-sicherheit-reisen': 'cyber-security',
  'cyber-security-travel-2026': 'cyber-security',
  'ciberseguridad-viajeros': 'cyber-security',
  'beste-travel-apps-2026': 'travel-apps',
  'best-travel-apps-2026': 'travel-apps',
  'mejores-apps-viaje-2026': 'travel-apps',

  // On the Move
  'zugreisen-europa': 'train-europe',
  'train-travel-europe': 'train-europe',
  'viajes-tren-europa': 'train-europe',
  'nachtzuege-europa-2026': 'night-train',
  'night-trains-europe-2026': 'night-train',
  'trenes-nocturnos-europa-2026': 'night-train',
  'roadtrip-etappen-planung': 'road-trip',
  'road-trip-stages-planning': 'road-trip',
  'roadtrip-planificacion-etapas': 'road-trip',
  'kreuzfahrt-staedte-verlaengern': 'cruise-port',
  'cruise-extend-port-cities': 'cruise-port',
  'cruceros-ampliar-ciudades': 'cruise-port',

  // Carry-On Only
  'nur-handgepaeck': 'carry-on-bag',
  'carry-on-only': 'carry-on-bag',
  'solo-equipaje-de-mano': 'carry-on-bag',
  'capsule-wardrobe-handgepaeck': 'capsule-wardrobe',
  'capsule-wardrobe-carry-on': 'capsule-wardrobe',
  'maleta-capsula-equipaje-mano': 'capsule-wardrobe',
  'powerbank-regeln-handgepaeck-2026': 'powerbank',
  'powerbank-rules-carry-on-2026': 'powerbank',
  'handgepaeck-fluessigkeiten-regeln-2026': 'carry-on-liquids',
  'carry-on-liquids-rules-2026': 'carry-on-liquids',
  'liquidos-equipaje-mano-2026': 'carry-on-liquids',

  // Travel Green
  'co2-kompensation-fliegen': 'forest-airplane',
  'flight-carbon-offsets-truth': 'forest-airplane',
  'compensacion-co2-vuelos': 'forest-airplane',
  'plastik-frei-reisen-tipps': 'reusable-bottle',
  'plastic-free-travel-tips': 'reusable-bottle',
  'viaje-sin-plastico-consejos': 'reusable-bottle',
  'slow-travel-bedeutet-was': 'slow-travel',
  'slow-travel-what-it-really-means': 'slow-travel',
  'slow-travel-que-significa': 'slow-travel',

  // Lifestyle / Special
  'workation-steuern-2026': 'workation',
  'workation-tax-rules-2026': 'workation',
  'workation-impuestos-2026': 'workation',
  'sabbatical-planen-guide': 'sabbatical',
  'sabbatical-planning-guide': 'sabbatical',
  'sabbatical-guia-planificacion': 'sabbatical',
  'solo-reisen-frauen-sicher': 'solo-female-travel',
  'solo-travel-women-safe-countries': 'solo-female-travel',
  'viaje-solo-mujeres-seguro': 'solo-female-travel',
  'mit-hund-europa-reisen': 'travel-with-dog',
  'traveling-with-dog-europe': 'travel-with-dog',
  'viajar-con-perro-europa': 'travel-with-dog',
  'reisen-mit-baby-erste-fluege': 'baby-travel',
  'traveling-with-baby-first-flights': 'baby-travel',
  'viajar-con-bebe-primer-vuelo': 'baby-travel',

  // Hotels (general)
  'boutique-hotels': 'boutique-hotel',
  'hoteles-boutique-guia': 'boutique-hotel',
  'riads-marokko-guide': 'morocco-riad',
  'morocco-riads-guide': 'morocco-riad',
  'riads-marruecos-guia': 'morocco-riad',

  // ===== WHERE TO STAY BATCH 3 (2026-05-09) =====
  // Antalya
  'wo-uebernachten-antalya': 'antalya',
  'where-to-stay-antalya': 'antalya',
  'donde-alojarse-antalya': 'antalya',
  // Phuket
  'wo-uebernachten-phuket': 'phuket',
  'where-to-stay-phuket': 'phuket',
  'donde-alojarse-phuket': 'phuket',
  // Taipei
  'wo-uebernachten-taipei': 'taipei',
  'where-to-stay-taipei': 'taipei',
  'donde-alojarse-taipei': 'taipei',
  // Venice
  'wo-uebernachten-venedig': 'venice',
  'where-to-stay-venice': 'venice',
  'donde-alojarse-venecia': 'venice',
  // Dublin
  'wo-uebernachten-dublin': 'dublin',
  'where-to-stay-dublin': 'dublin',
  'donde-alojarse-dublin': 'dublin',
  // Doha
  'wo-uebernachten-doha': 'doha',
  'where-to-stay-doha': 'doha',
  'donde-alojarse-doha': 'doha',
  // Abu Dhabi
  'wo-uebernachten-abu-dhabi': 'abu-dhabi',
  'where-to-stay-abu-dhabi': 'abu-dhabi',
  'donde-alojarse-abu-dhabi': 'abu-dhabi',
  // Ho Chi Minh City
  'wo-uebernachten-ho-chi-minh-stadt': 'ho-chi-minh',
  'where-to-stay-ho-chi-minh-city': 'ho-chi-minh',
  'donde-alojarse-ho-chi-minh': 'ho-chi-minh',
  // Toronto
  'wo-uebernachten-toronto': 'toronto',
  'where-to-stay-toronto': 'toronto',
  'donde-alojarse-toronto': 'toronto',
  // Stockholm
  'wo-uebernachten-stockholm': 'stockholm',
  'where-to-stay-stockholm': 'stockholm',
  'donde-alojarse-estocolmo': 'stockholm',

  // ===== WHERE TO STAY BATCH 2 (2026-05-09) =====
  // Dubai
  'wo-uebernachten-dubai': 'dubai',
  'where-to-stay-dubai': 'dubai',
  'donde-alojarse-dubai': 'dubai',
  // Kuala Lumpur
  'wo-uebernachten-kuala-lumpur': 'kuala-lumpur',
  'where-to-stay-kuala-lumpur': 'kuala-lumpur',
  'donde-alojarse-kuala-lumpur': 'kuala-lumpur',
  // Osaka
  'wo-uebernachten-osaka': 'osaka',
  'where-to-stay-osaka': 'osaka',
  'donde-alojarse-osaka': 'osaka',
  // Milan
  'wo-uebernachten-mailand': 'milan',
  'where-to-stay-milan': 'milan',
  'donde-alojarse-milan': 'milan',
  // Sydney
  'wo-uebernachten-sydney': 'sydney',
  'where-to-stay-sydney': 'sydney',
  'donde-alojarse-sydney': 'sydney',
  // Copenhagen
  'wo-uebernachten-kopenhagen': 'copenhagen',
  'where-to-stay-copenhagen': 'copenhagen',
  'donde-alojarse-copenhague': 'copenhagen',
  // Porto (Where to Stay — shares photo with porto topic)
  'wo-uebernachten-porto': 'porto',
  'where-to-stay-porto': 'porto',
  'donde-alojarse-oporto': 'porto',
  // Kyoto
  'wo-uebernachten-kyoto': 'kyoto',
  'where-to-stay-kyoto': 'kyoto',
  'donde-alojarse-kioto': 'kyoto',
  // Tbilisi
  'wo-uebernachten-tiflis': 'tbilisi',
  'where-to-stay-tbilisi': 'tbilisi',
  'donde-alojarse-tiflis': 'tbilisi',
  // Valencia
  'wo-uebernachten-valencia': 'valencia',
  'where-to-stay-valencia': 'valencia',
  'donde-alojarse-valencia': 'valencia',

  // Havana
  'wo-uebernachten-havanna': 'havana',
  'where-to-stay-havana': 'havana',
  'donde-alojarse-la-habana': 'havana',
  // Vancouver
  'wo-uebernachten-vancouver': 'vancouver',
  'where-to-stay-vancouver': 'vancouver',
  'donde-alojarse-vancouver': 'vancouver',
  // Chicago
  'wo-uebernachten-chicago': 'chicago',
  'where-to-stay-chicago': 'chicago',
  'donde-alojarse-chicago': 'chicago',

  // ===== NEW BATCH (2026-05-09) =====
  // Greek Islands
  'griechenland-inseln-vergleich': 'greek-islands',
  'greek-islands-comparison': 'greek-islands',
  'islas-griegas-comparativa': 'greek-islands',
  // Thailand
  'thailand-route-2-wochen': 'thailand',
  'thailand-2-week-itinerary': 'thailand',
  'tailandia-2-semanas-ruta': 'thailand',
  // Dubai
  'dubai-reiseguide': 'dubai',
  'dubai-travel-guide': 'dubai',
  'dubai-guia-viaje': 'dubai',
  // Hotel Upgrade
  'hotel-upgrade-gratis-tipps': 'hotel-upgrade',
  'hotel-upgrade-free-tips': 'hotel-upgrade',
  'trucos-upgrade-hotel-gratis': 'hotel-upgrade',
  // Family Travel Europe
  'familienurlaub-europa-ziele': 'family-vacation',
  'family-travel-europe-best-destinations': 'family-vacation',
  'viaje-familiar-europa-mejores-destinos': 'family-vacation',
  // Budget Travel
  'reisen-kleines-budget-tipps': 'budget-travel',
  'travel-tight-budget-tips': 'budget-travel',
  'viajar-con-poco-dinero-consejos': 'budget-travel',
  // Autumn Travel
  'beste-herbstziele-reisen': 'autumn-travel',
  'best-autumn-travel-destinations': 'autumn-travel',
  'mejores-destinos-otono-viaje': 'autumn-travel',
  // Maldives
  'malediven-reiseguide-tipps': 'maldives',
  'maldives-travel-guide-tips': 'maldives',
  'maldivas-guia-viaje-2026': 'maldives',
  // Luxury on Budget
  'luxusreisen-guenstig-tipps': 'luxury-travel',
  'luxury-travel-budget-tips': 'luxury-travel',
  'viaje-lujo-economico-trucos': 'luxury-travel',
  // Japan Beyond Tokyo
  'japan-jenseits-von-tokio': 'japan-kyoto',
  'japan-beyond-tokyo-guide': 'japan-kyoto',
  'japon-mas-alla-de-tokio': 'japan-kyoto',

  // ===== REPLACEMENT BATCH (2026-05-09) — replaces deleted forbidden destinations =====
  // Dubrovnik
  'wo-uebernachten-dubrovnik': 'dubrovnik',
  'where-to-stay-dubrovnik': 'dubrovnik',
  'donde-alojarse-dubrovnik': 'dubrovnik',
  // Reykjavik
  'wo-uebernachten-reykjavik': 'reykjavik',
  'where-to-stay-reykjavik': 'reykjavik',
  'donde-alojarse-reikiavik': 'reykjavik',
  // Krakow
  'wo-uebernachten-krakau': 'krakow',
  'where-to-stay-krakow': 'krakow',
  'donde-alojarse-cracovia': 'krakow',
  // Valletta
  'wo-uebernachten-valletta': 'valletta',
  'where-to-stay-valletta': 'valletta',
  'donde-alojarse-la-valeta': 'valletta',
  // Chiang Mai
  'wo-uebernachten-chiang-mai': 'chiang-mai',
  'where-to-stay-chiang-mai': 'chiang-mai',
  'donde-alojarse-chiang-mai': 'chiang-mai',
  // Nairobi
  'wo-uebernachten-nairobi': 'nairobi',
  'where-to-stay-nairobi': 'nairobi',
  'donde-alojarse-nairobi': 'nairobi',
};

// Topic key -> Unsplash search query (used when downloading)
export const topicToQuery = {
  // Cities
  'amsterdam': 'amsterdam canal houses',
  'athens': 'athens acropolis greece',
  'budapest': 'budapest parliament danube river',
  'florence': 'florence italy duomo tuscany',
  'istanbul': 'istanbul bosphorus turkey mosque',
  'munich': 'munich marienplatz bavaria',
  'santorini': 'santorini white houses blue dome greece',
  'booking-genius': 'hotel deal booking laptop',
  'carry-on-liquids': 'airport security liquids bag 100ml',
  'bali': 'bali rice terraces ubud',
  'bangkok': 'bangkok temple skyline',
  'barcelona': 'barcelona sagrada familia',
  'berlin': 'berlin brandenburg gate',
  'bogota': 'bogota colombia',
  'buenos-aires': 'buenos aires colorful houses',
  'cancun': 'cancun beach turquoise water',
  'cape-town': 'cape town table mountain',
  'cartagena': 'cartagena colombia colorful',
  'cusco': 'cusco peru plaza',
  'edinburgh': 'edinburgh castle scotland',
  'hanoi': 'hanoi old quarter vietnam',
  'hong-kong': 'hong kong skyline',
  'las-vegas': 'las vegas strip neon',
  'lima': 'lima peru pacific coast',
  'lisbon': 'lisbon yellow tram portugal',
  'london': 'london big ben thames',
  'los-angeles-city': 'los angeles palm trees',
  'madrid': 'madrid plaza mayor',
  'marrakech': 'marrakech morocco medina',
  'marseille': 'marseille old port',
  'medellin': 'medellin colombia',
  'mendoza': 'mendoza vineyards andes',
  'mexico-city': 'mexico city zocalo',
  'miami': 'miami beach art deco',
  'new-orleans': 'new orleans french quarter',
  'new-york': 'new york skyline manhattan',
  'paris': 'paris eiffel tower',
  'porto': 'porto portugal douro river',
  'prague': 'prague old town charles bridge',
  'rio-de-janeiro': 'rio de janeiro christ redeemer',
  'rome': 'rome colosseum',
  'san-francisco': 'san francisco golden gate',
  'seoul': 'seoul south korea',
  'seville': 'seville spain plaza',
  'singapore': 'singapore marina bay sands',
  'tokyo': 'tokyo neon street',
  'tulum': 'tulum mayan ruins beach',
  'vienna': 'vienna austria',

  // Topic-specific
  'tokyo-food': 'tokyo ramen sushi food',
  'ferrari-museum': 'ferrari sports car red',
  'puglia': 'puglia trulli alberobello',
  'albania-coast': 'albania ksamil beach',
  'faroe-islands': 'faroe islands cliffs',
  'iceland': 'iceland waterfall aurora',
  'patagonia': 'patagonia mountains torres del paine',
  'zanzibar': 'zanzibar stone town',
  'slovenia': 'slovenia bled lake',
  'santiago-de-compostela': 'santiago de compostela cathedral',
  'northern-lights': 'northern lights aurora borealis',
  'europe-hidden': 'europe hidden alpine village',
  'costa-rica': 'costa rica rainforest beach',
  'costa-rica-surf': 'costa rica surfing waves',

  // Travel topics
  'flights-cheap': 'airplane window clouds',
  'flights-booking': 'flight ticket calendar',
  'world-map': 'world map travel pin',
  'flight-ticket': 'boarding pass passport',
  'business-class': 'business class airplane seat',
  'airport-lounge': 'airport lounge premium',
  'airport': 'airport terminal travelers',
  'jet-lag': 'sleeping airplane window',
  'stopover': 'airport layover transfer',
  'ai-travel': 'laptop travel map',
  'ai-vs-agent': 'travel agent computer',
  'ai-tools': 'smartphone travel apps',
  'ai-comparison': 'computer screen comparison',
  'travel-planning': 'travel planning notebook map',
  'travel-journal': 'travel notebook journal pen',
  'hotel-booking': 'hotel reception lobby',
  'apartment-vs-hotel': 'modern apartment interior',
  'rental-car': 'rental car keys road',
  'rental-car-keys': 'car keys hand',
  'car-keys-money': 'car money savings',
  'travel-insurance': 'travel insurance documents',
  'cyber-security': 'laptop security travel',
  'travel-apps': 'smartphone travel app',
  'train-europe': 'european train alps scenic',
  'night-train': 'sleeper train cabin night',
  'train-station': 'train station platform europe',
  'road-trip': 'road trip mountain highway',
  'cruise-port': 'cruise ship port mediterranean',
  'carry-on-bag': 'carry on luggage suitcase',
  'capsule-wardrobe': 'minimalist clothes folded suitcase',
  'powerbank': 'phone charging cable airport',
  'forest-airplane': 'green forest aerial view',
  'reusable-bottle': 'reusable water bottle nature',
  'slow-travel': 'slow travel hammock',
  'workation': 'laptop beach workation',
  'sabbatical': 'sabbatical mountain hiking',
  'solo-female-travel': 'woman solo traveler backpack',
  'travel-with-dog': 'dog travel adventure',
  'baby-travel': 'baby airplane travel',
  'boutique-hotel': 'boutique hotel room interior',
  'morocco-riad': 'morocco riad courtyard',
  // New topics 2026-05-09
  'greek-islands': 'greek islands white houses blue dome',
  'thailand': 'thailand temple bangkok golden',
  'dubai': 'dubai skyline burj khalifa',
  'hotel-upgrade': 'luxury hotel suite interior upgrade',
  'family-vacation': 'family travel beach children happy',
  'budget-travel': 'budget backpacker travel hostel',
  'autumn-travel': 'autumn fall foliage travel landscape',
  'maldives': 'maldives overwater bungalow turquoise',
  'luxury-travel': 'luxury hotel infinity pool ocean',
  'japan-kyoto': 'kyoto japan bamboo geisha temple',
  // New city topics for Where to Stay batch 3
  'antalya': 'antalya turkey old town harbor turquoise',
  'phuket': 'phuket thailand beach big buddha temple',
  'taipei': 'taipei taiwan 101 skyline night',
  'venice': 'venice italy canal gondola sunset',
  'dublin': 'dublin ireland temple bar colorful',
  'doha': 'doha qatar skyline corniche tower',
  'abu-dhabi': 'abu dhabi grand mosque white dome',
  'ho-chi-minh': 'ho chi minh city vietnam motorbike street',
  'toronto': 'toronto canada cn tower lake ontario',
  'stockholm': 'stockholm sweden gamla stan old town',
  'havana': 'havana cuba colorful colonial cars',
  'vancouver': 'vancouver canada mountains ocean harbour',
  'chicago': 'chicago skyline lake michigan architecture',
  // New city topics for Where to Stay batch 2
  'kuala-lumpur': 'kuala lumpur petronas towers skyline night',
  'osaka': 'osaka japan dotonbori neon reflections',
  'milan': 'milan italy cathedral duomo piazza',
  'sydney': 'sydney opera house harbour bridge australia',
  'copenhagen': 'copenhagen nyhavn colorful canal denmark',
  'kyoto': 'kyoto japan temple bamboo garden',
  'tbilisi': 'tbilisi georgia old town church sulfur',
  'valencia': 'valencia spain city arts sciences',
  // Replacement batch (2026-05-09)
  'dubrovnik': 'dubrovnik croatia old town adriatic walls',
  'reykjavik': 'reykjavik iceland colorful houses hallgrimskirkja',
  'krakow': 'krakow poland old town main market square',
  'valletta': 'valletta malta grand harbour baroque architecture',
  'chiang-mai': 'chiang mai thailand temple wat',
  'nairobi': 'nairobi kenya skyline africa city modern',
};
